### ISSUE TITLE
Can anybody share some fail cases, including B-spline images and parameters(grid&k). Thanks

### ISSUE THREAD

**Issue by yuedajiong** [KindXiaoming/pykan#100]
as title, thanks.

including: scale_spline, c:

c = coef2curve(coef=self.coef[self.weight_sharing],  x_eval=i, grid=self._grid[self.weight_sharing], k=self.k).permute(1,0)
self.scale_spline.unsqueeze(dim=0) * c

**Comment by KindXiaoming** [comment]
close for now, feel free to open if there's more update
