### ISSUE TITLE
How to Extract Predicted Values

### ISSUE THREAD

**Issue by rxa615** [KindXiaoming/pykan#101]
Firstly, I would like to congratulate the KAN team on their outstanding work. I am currently implementing the KAN for genetic data. My question is, how can we extract the predicted values from the trained model, similar to using model.predict()?

**Comment by ZacksterUG** [comment]
Like this 
![image](https://github.com/KindXiaoming/pykan/assets/48206034/5ae02807-4d35-44bf-8697-849eae5017b1)

**Comment by yuedajiong** [comment]
easy!

1. inference-only mode: You can mimic the logic of training, train and save a checkpoint. During inference, load the checkpoint, prepare the data directly, call forward, and get what you want.
2. If you want to get results during training, LBFGS is not very intuitive as it requires a closure; you can get it within the closure. If using Adam/SGD, you can directly obtain the predicted results within the training loop.
