### ISSUE TITLE
Has anyone tested some functions other than basic functions?

### ISSUE THREAD

**Issue by yuedajiong** [KindXiaoming/pykan#104]
np.sin(3*i)*np.random.binomial(n=1,p=0.5,size=1)   binomial其他也行

封闭曲线  多值函数

带有阶次和求和的，比如Weierstrass等这种形式的

......

我有一个问题： 对于复杂问题，选择基函数困难，还是函数复合形式困难？  
这个问题背后的一个例子就是： 采用傅里叶级数的做法，可以用若干不同周期组合起来，画出非常漂亮好玩的图画。  这里基函数也不用选了，单反过来，假设给定任意一个人的一张脸，要求出这个函数复合形式，感觉就很难的样子。 （我没有深入研究过这个，知识凭直觉。）

**Comment by KindXiaoming** [comment]
close for now, feel free to reopen if there's more update
