### ISSUE TITLE
RuntimeError: expected scalar type Double but found Float

### ISSUE THREAD

**Issue by 1457009544** [KindXiaoming/pykan#105]

**Comment by 1457009544** [comment]
I tried to run the provided example of the classification task, but encountered an error.
Anaconda3/envs/langchain/lib/python3.9/site-packages/torch/functional.py", line 360, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: expected scalar type Double but found Float

**Comment by leehangyue** [comment]
I encountered a similar error with the same error message when calling torch.nn.MSELoss()(prediction, target).backward(). In my case the problem was solved by converting all relevant fields in KAN.forward and KANLayer.__init__ to torch.float32 or any other dtype conforming with the input tensor x.

**Comment by 1457009544** [comment]
> I encountered a similar error with the same error message when calling torch.nn.MSELoss()(prediction, target).backward(). In my case the problem was solved by converting all relevant fields in KAN.forward and KANLayer.**init** to torch.float32 or any other dtype conforming with the input tensor x.

Yes, I am also trying to modify this part ：coef2curve . I found that modifying coef and B_batch can solve this problem. Thank you for your help.
