### ISSUE TITLE
Corresponding explanation

### ISSUE THREAD

**Issue by ghost** [KindXiaoming/pykan#109]
Hello, what is the proof that kan and mlp are dual?

**Comment by brayevalerien** [comment]
You can read the full paper at: https://arxiv.org/abs/2404.19756
The section where they define the KANs should be sufficient

**Comment by SLATT-dev** [comment]
Do you use the article "Duality between two generalized.." by Wang Y. et al?

**Comment by brayevalerien** [comment]
I've not read the paper you are mentioning yet, but there is a [discussion about this topic on Reddit](https://www.reddit.com/r/MachineLearning/comments/1clcu5i/d_kolmogorovarnold_network_is_just_an_mlp/).
The OP has shared a [notebook](https://colab.research.google.com/drive/1v3AHz5J3gk-vu4biESubJdOsUheycJNz#scrollTo=bzGAJGX6BsLW) where they show how one can build an MLP equivalent to a give KAN.

**Comment by SLATT-dev** [comment]
Thanks!

**Comment by brayevalerien** [comment]
You're welcome. This is a pretty interesting topic and even thought the collab notebook only shows how they are equivalent on a piecewise linear fonction, I'm confident it can be generalized to any continous function with large enough MLPs.

**Comment by AlessandroFlati** [comment]
Spoiler: it can. Unfortunately, this comment is too narrow to write down the proof. (semi-quote)
