### ISSUE TITLE
Please provide a description of the basis functions B_i

### ISSUE THREAD

**Issue by alexjwilliams** [KindXiaoming/pykan#11]
Unless I missed something, the paper does not include one. It appears that the B_i are computed using the "Cox–de Boor recursion formula", or something similar (https://en.wikipedia.org/wiki/B-spline#Definition): https://github.com/KindXiaoming/pykan/blob/6a5b99f45601a1282053f14f97e70a8bb24f8b2a/kan/spline.py#L56-L60

**Comment by KindXiaoming** [comment]
That's correct, my implementation follows that wiki page. The indices in the code might be a bit different from the wiki page.

**Comment by alexjwilliams** [comment]
Thank you. You might consider including a brief mention of that in your paper, and/or here: https://github.com/KindXiaoming/pykan/blob/c63ff0404d0e7a4e900a492137d51e6c4bc1e085/tutorials/API_3_grid.ipynb#L76 One of the questions that came to me immediately when I was reading was "what are B_i?".
