### ISSUE TITLE
expected scalar type Double but found Float: Occurred when trying to implement example 3.

### ISSUE THREAD

**Issue by XuBuling** [KindXiaoming/pykan#113]
Code: 
from kan import KAN
import matplotlib.pyplot as plt
from sklearn.datasets import make_moons
import torch
import numpy as np

dataset = {}
train_input, train_label = make_moons(n_samples=1000, shuffle=True, noise=0.1, random_state=None)
test_input, test_label = make_moons(n_samples=1000, shuffle=True, noise=0.1, random_state=None)

dataset['train_input'] = torch.from_numpy(train_input)
dataset['test_input'] = torch.from_numpy(test_input)
dataset['train_label'] = torch.from_numpy(train_label[:,None])
dataset['test_label'] = torch.from_numpy(test_label[:,None])

X = dataset['train_input']
y = dataset['train_label']
plt.scatter(X[:,0], X[:,1], c=y[:,0])

model = KAN(width=[2,1], grid=3, k=3)

def train_acc():
    return torch.mean((torch.round(model(dataset['train_input'])[:,0]) == dataset['train_label'][:,0]).float())

def test_acc():
    return torch.mean((torch.round(model(dataset['test_input'])[:,0]) == dataset['test_label'][:,0]).float())

results = model.train(dataset, opt="LBFGS", steps=20, metrics=(train_acc, test_acc));
results['train_acc'][-1], results['test_acc'][-1]

--------------------------------------------------------

description:   0%|                                                           | 0/20 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\19827\Documents\KAN\pykan-env\classification.py", line 28, in <module>
    results = model.train(dataset, opt="LBFGS", steps=20, metrics=(train_acc, test_acc));
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\19827\Documents\KAN\pykan-env\Lib\site-packages\kan\KAN.py", line 898, in train
    self.update_grid_from_samples(dataset['train_input'][train_id].to(device))
  File "C:\Users\19827\Documents\KAN\pykan-env\Lib\site-packages\kan\KAN.py", line 243, in update_grid_from_samples
    self.forward(x)
  File "C:\Users\19827\Documents\KAN\pykan-env\Lib\site-packages\kan\KAN.py", line 311, in forward
    x_numerical, preacts, postacts_numerical, postspline = self.act_fun[l](x)
                                                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\19827\Documents\KAN\pykan-env\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\19827\Documents\KAN\pykan-env\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\19827\Documents\KAN\pykan-env\Lib\site-packages\kan\KANLayer.py", line 173, in forward
    y = coef2curve(x_eval=x, grid=self.grid[self.weight_sharing], coef=self.coef[self.weight_sharing], k=self.k, device=self.device)  # shape (size, batch)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\19827\Documents\KAN\pykan-env\Lib\site-packages\kan\spline.py", line 100, in coef2curve
    y_eval = torch.einsum('ij,ijk->ik', coef, B_batch(x_eval, grid, k, device=device))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\19827\Documents\KAN\pykan-env\Lib\site-packages\torch\functional.py", line 385, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: expected scalar type Double but found Float

**Comment by XuBuling** [comment]
I'm using the newest version of KAN, but this problem still exists. Also, I've looked at the #105 and tried to modify the KANLayer file, but I cannot find where to modify the dtype. Need help!

**Comment by Jim137** [comment]
Hi,
I attempted to resolve by converting the input to float before converting it to a Tensor.
```python
dataset['train_input'] = torch.from_numpy(train_input.astype(np.float32))
dataset['test_input'] = torch.from_numpy(test_input.astype(np.float32))
```
This approach successfully addressed the problem for me. Hope it will help you.

**Comment by XuBuling** [comment]
Thanks so much Jim! Your solution works properly!
