### ISSUE TITLE
Extracting symbolic activation functions

### ISSUE THREAD

**Issue by WJiangH** [KindXiaoming/pykan#116]
Hi, 

I have a question about extracting symbolic activation functions after fixed symbolic for each activation functions in KAN models. The tutorial shows how to get the activation function values and I am wondering is there built-in functions for output the symbolic formula for each activation function.

Thanks,
JJ

**Comment by KindXiaoming** [comment]
`model.symbolic_fun[l].funs_name[j][i]`
