### ISSUE TITLE
Error installing via pip

### ISSUE THREAD

**Issue by kvndhrty** [KindXiaoming/pykan#13]
Hi folks,

When I clone and install using ```pip install -e .```, I get an error reading the long description from the ```README.md``` file. 

Error Message
> ```Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\K\Documents\Research\GitHub\pykan\setup.py", line 5, in <module>
>           long_description = fh.read()
>         File "C:\Users\K\Anaconda3\envs\tkc\lib\encodings\cp1252.py", line 23, in decode
>           return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>       UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 4711: character maps to <undefined>```

If you change line 4 in ```setup.py``` from ```with open("README.md", "r") as fh:``` to ```with open("README.md", "r", encoding="utf8") as fh:```, it solves the error for me.

**Comment by KindXiaoming** [comment]
Thanks for the catch!

**Comment by kvndhrty** [comment]
Ah that makes sense, yes I'm on windows :)

**Comment by kvndhrty** [comment]
I suppose I can close this too!

**Comment by viktor-ktorvi** [comment]
I noticed this too.  Setting:

```python
with open("README.md", "r", encoding="utf8") as fh:
    long_description = fh.read()
```

In [setup.py](https://github.com/KindXiaoming/pykan/blob/c63ff0404d0e7a4e900a492137d51e6c4bc1e085/setup.py#L4) should fix it. I can make a PR, I just didn't want to spam PRs yesterday hehe
