### ISSUE TITLE
Is it okay to use KAN for something other than PDE calculations, like MLP?

### ISSUE THREAD

**Issue by pop756** [KindXiaoming/pykan#131]
Is it acceptable to use KAN as a way to approximate f(x) when computing expressions such as y = g(f(x)) over other layers or functions rather than over a function for y = f(x), and are there any disadvantages to using adam as an optimizer rather than LBFGS for KAN models?

**Comment by KindXiaoming** [comment]
yes, totally! Just that I need high precision and my models aren't so big, I used LBFGS. if you don't need high precision or need efficiency, Adam is better.
