### ISSUE TITLE
Cut off all the branches

### ISSUE THREAD

**Issue by plumv** [KindXiaoming/pykan#149]
When I first demonstrated using Kan for a demo, the actual execution of the code was not the same as in the sample.
I found that when constructing nodes, some nodes can also be trimmed.
I don't know if it's possible to optimize the pruning logic so that the minimum model can be achieved every time the pruning is done

Device: Mac Pro M1

Student: https://kindxiaoming.github.io/pykan/intro.html#hello-kan

**Comment by plumv** [comment]
Actual operating results

<img width="1243" alt="image" src="https://github.com/KindXiaoming/pykan/assets/51311810/29620bf8-718d-4512-8525-7398826a09bf">
<img width="1207" alt="image" src="https://github.com/KindXiaoming/pykan/assets/51311810/9dbe4b0c-9261-4a73-bc0d-c2aaa99f11f0">

**Comment by AlessandroFlati** [comment]
Could you print `symbolic_formula[0][0]` and/or share the notebook please?

**Comment by plumv** [comment]
<img width="760" alt="image" src="https://github.com/KindXiaoming/pykan/assets/51311810/6053884d-1c09-4f41-b02a-c781a3a65524">

**Comment by AlessandroFlati** [comment]
Ok, this adds valuable information for me. 
The point is that the network, altough "pruned", is still a forward connected graph - so even if you don't see the edges, they're actually there nonetheless. Their contribution is minimal, though. You can probably see it if you print out `model.symbolic_formula(simplify=True)[0][0]`.

You're right in saying that if this was a graph network, it should actually prune the node (1, 0) and the edges (0,0,0), (0, 1, 0), (1, 0, 0). But for how is structured right now, it won't. 

If you're willing, you can add this consideration inside the #123 or on a new Issue.

**Comment by KindXiaoming** [comment]
hi, you may want to try a higher threshold in `model.prune(threshold=5e-2)`
