### ISSUE TITLE
Odd behavior of training process in almost-machine-precision function fitting. 

### ISSUE THREAD

**Issue by AlessandroFlati** [KindXiaoming/pykan#154]
https://gist.github.com/AlessandroFlati/a4f5d23864bca30f2b96c1052efdc140

**Comment by AlessandroFlati** [comment]
Please note that this is just an experiment - of course I know this is not the optimal way of training `xy` function.

**Comment by AlessandroFlati** [comment]
![image](https://github.com/KindXiaoming/pykan/assets/12647648/00bbe43d-eb59-4608-a80a-e2f4a592162e)

Memorandum: never trust `symbolic_formula` without `simplify = True`, because it just trims down floating digits of the coefficient, while the result is actually correct (even if not "natural"). There was actually no problem with the trained model.

That said, is utterly strange that the "minimal" model won't learn this function even if we fix everything.
https://gist.github.com/AlessandroFlati/1934c6ba922388220f0a92acdc6cadfa

**Comment by KindXiaoming** [comment]
Maybe the most update-to-date version  0.2.0 solves this (at least partially). `symbolic_formula()` no longer does rounding, instead the user needs to specify how to do the rounding. 
Example for multiplication:
https://github.com/KindXiaoming/pykan/blob/master/tutorials/Interp_1_Hello%2C%20MultKAN.ipynb
