### ISSUE TITLE
Hi! I made a KAN-based diffusion model, with quite good results

### ISSUE THREAD

**Issue by kabachuha** [KindXiaoming/pykan#160]
Hi! I made a test of how KAN could assist denoising diffusion and adapted the very initial spiral-diffusion model utilizing an MLP to KAN.

You can see that a two layer KAN fares almost as good as a 4-layer MLP (despite having 30% less parameters), and the 4-layer KAN vastly outperforming it.

![loss-comparison](https://github.com/KindXiaoming/pykan/assets/14872007/fde3c990-5a21-4b59-a828-e978ab48e377)

I think it would be worth to add a notebook with diffusion to this repository, at least for educational purposes, and for gaining more mainstream attention.

Additionally, it could be nice to explore if it learned some good functions in the layers.

https://github.com/kabachuha/kan-diffusion

---

Same structure KAN:

![s2](https://github.com/KindXiaoming/pykan/assets/14872007/77141666-4a43-4fcd-b5f9-abcf241d963a)

MLP:

![mlp-s2](https://github.com/KindXiaoming/pykan/assets/14872007/c8f4fb16-1705-47d4-bb94-c7d45d39f353)

2-layer KAN:

![smol-kan-s2](https://github.com/KindXiaoming/pykan/assets/14872007/2dcde021-037e-4bab-853d-83b3d09dc010)

**Comment by KindXiaoming** [comment]
Thanks for implementing this! This is one experiment in my mind but never got a chance to do. The score field is kind of multiscale, which might be why KANs can outperform MLP. Would also be fun to look at approximation abilities for KANs and MLPs in near/immediate/far fields? Do KANs outperform MLPs mostly in nearly fields (If what I said above makes sense)?

**Comment by kabachuha** [comment]
I'm not so well-versed in the math base myself, is it something like looking at losses for each timesteps?

Anyway, I think it would be a great community experiment

**Comment by 1ssb** [comment]
This is not strictly generalised. I tried it with an image diffusion model replacing the MLPs with the equivalently layered KANs, the generalisation is poor. I have elaborated on a more pathological example in the functional approximation. MLPs are still outperforming KANs. Any insights?

**Comment by AlessandroFlati** [comment]
> MLPs are still outperforming KANs.

Wow, a single example proves that an entire branch of techniques and methods are useless.

**Comment by KindXiaoming** [comment]
I think generative modeling is particuarly subtle because two goals are not necessarily aligned: (1) fit score function well; (2) being able to generalize. This experiment seems like a good starting point, definitely agree this is a community effort. Again, great initiative!

**Comment by HaiFengZeng** [comment]
amazing! can you share  this toy code
