### ISSUE TITLE
Are KANs RBF Networks?

### ISSUE THREAD

**Issue by ZiyaoLi** [KindXiaoming/pykan#162]
#141 proposes [FastKAN](https://github.com/ZiyaoLi/fast-kan) which uses 1D Gaussian RBF basis to replace the 3-order B-spline basis used in KAN. By doing so, KANs are in fact turned into an RBF network with univariate distances.

This issue welcomes more discussions over the relationships between KANs and RBF Networks. Personally I'm not an expert in RBFs so expertise is warmly welcome.

**Comment by AthanasiosDelis** [comment]
I think this property generalizes, and KANs can be approximated with many different configurations of exponential-based functions, not only RBFs. I have had successful experiments with Reflectional SWitch Activation Function (RSWAF):
![image](https://github.com/KindXiaoming/pykan/assets/68398213/81c55f83-2b9e-4513-ab39-09dcddd9db5a)
I have posted my findings in:
https://github.com/KindXiaoming/pykan/issues/141
You can also check the code in my repo for thoughtful criticism and commenting:
https://github.com/AthanasiosDelis/faster-kan
