### ISSUE TITLE
Runtime Error in hellokan.ipynb

### ISSUE THREAD

**Issue by wkqian06** [KindXiaoming/pykan#170]
I met the same issue that appeared in the previously closed issues #117 #46 #89

```
File ...\pykan\kan\spline.py:135, in curve2coef(x_eval, y_eval, grid, k, device)
    133 # x_eval: (size, batch); y_eval: (size, batch); grid: (size, grid); k: scalar
    134 mat = B_batch(x_eval, grid, k, device=device).permute(0, 2, 1)
--> 135 coef = torch.linalg.lstsq(mat.to('cpu'), y_eval.unsqueeze(dim=2).to('cpu')).solution[:, :, 0]  # sometimes 'cuda' version may diverge
    136 return coef.to(device)

RuntimeError: false INTERNAL ASSERT FAILED at "...\pytorch\\pytorch\\builder\\windows\\pytorch\\aten\\src\\ATen\\native\\BatchLinearAlgebra.cpp":1540, please report a bug to PyTorch. torch.linalg.lstsq: (Batch element 0): Argument 6 has illegal value. Most certainly there is a bug in the implementation calling the backend library.
```
Changing the opt to 'Adam' did not solve the problem. 

It seems that the driver in _torch.linalg.lstsq_  should be specifically claimed instead of using 'None'. 

Either 'LBFGS' or 'Adam' works when I use the following if statement in _curve2coef_  though I don't know why.

```
    if device == 'cpu':
        coef = torch.linalg.lstsq(mat.to(device), y_eval.unsqueeze(dim=2).to(device),driver = 'gelsy').solution[:, :, 0]
    else: 
        coef = torch.linalg.lstsq(mat.to(device), y_eval.unsqueeze(dim=2).to(device),driver = 'gels').solution[:, :, 0]  # sometimes 'cuda' version may diverge
```

**Comment by AlessandroFlati** [comment]
This seems promising, I'll test it too! Can you explain the difference between `driver = 'gelsy'` and `driver = 'gels'`?
Also, probably that if block can be rewritten as 
`coef = torch.linalg.lstsq(mat.to(device), y_eval.unsqueeze(dim=2).to(device),driver = 'gelsy' if device == 'cpu' else 'gels').solution[:, :, 0]`

**Comment by wkqian06** [comment]
Honestly, I don't know in detail. According to the _[torch.linalg.lstsq](https://pytorch.org/docs/stable/generated/torch.linalg.lstsq.html)_ document, _gelsy_ is a general QR factorization to solve least-squares using CPU. _gels_ assumes the matrix is full rank. For cuda, _gels_ is the only choice. 

Something weird is that if the driver is set to _None_, as what the original code did, the driver should be automatically set to either _gelsy_ or _gels_ depending on the device setting. Then, the issue appears.

**Comment by AlessandroFlati** [comment]
Well I think we can easily make a PR for this annoying bug with your suggestion (maybe just make it a oneliner as described above). If you're unsure how to do that, I'll take care of it.

**Comment by wkqian06** [comment]
Sure, please go ahead. I'm new to the GitHub collaboration. Glad this could help.
