### ISSUE TITLE
How exactly KAN can better interpreted than MLP?

### ISSUE THREAD

**Issue by mandar-gite** [KindXiaoming/pykan#175]
It is not clear why KAN can be interpreted better than MLP ?

**Comment by AlessandroFlati** [comment]
Did you at least read the paper and the documentation of this package?
One of the fundamental things pykan is able to do is symbolic transformation, i.e. you are able of expliciting the model formula itself. Every activation is a (smooth) function itself, easily plottable and applicable. I could continue, but I think I already gave too much explanations.

**Comment by mandar-gite** [comment]
Yes you did I guess .


I read the paper twice and read the documentation too .

I could not connect the idea . Thanks for explaining it to me.

**Comment by mandar-gite** [comment]
Also , can I some how help in making it super easy to understand . Let me
know  what you think?
