### ISSUE TITLE
hellokan.ipynb returns NaN instead of formula.

### ISSUE THREAD

**Issue by Stealeristaken** [KindXiaoming/pykan#179]
Hi. 

I was trying hellokan.ipynb file. I do some scaleup at training steps like 50 -> 150. In the end train_loss started to return NaN instead of any value.

I thought maybe it's a kernel error. So I re-downloaded the baseline hellokan.ipynb and rerun without any editing. It returned NaN once again. I will drop screenshot about problem.
<img width="1119" alt="Ekran Resmi 2024-05-13 15 08 12" src="https://github.com/KindXiaoming/pykan/assets/109769982/64620446-d24d-4782-9228-e2ce0145ceaf">

**Comment by KindXiaoming** [comment]
Hi, the problem was caused by the appearance of the log function (which is unexpected behavior). This means that the pruning step is not good. Could you show the plot you after pruning? From feedback from other, you may try `model.prune(threshold=5e-2)` instead of just `model.prune()`.

**Comment by Stealeristaken** [comment]
Sorry for late response. I tried both prune options (no-specified threshold and specified threshold) result was the same i am adding pictures 
```specified```

![Ekran Resmi 2024-05-16 20 46 51](https://github.com/KindXiaoming/pykan/assets/109769982/121524d3-f3eb-4a1b-961e-89bcea494f1d)

```no-specified```

![Ekran Resmi 2024-05-16 20 45 17](https://github.com/KindXiaoming/pykan/assets/109769982/89fc66bf-8b56-4dec-a448-65712afd2cfe)

**Comment by ShuleiCao** [comment]
I encountered a similar issue, but I found that increasing the step size helped.

**Comment by KindXiaoming** [comment]
@Stealeristaken, in block [8], it should again specify the threshold `model = model.prune(threshold=5e-2)`

**Comment by KindXiaoming** [comment]
@ShuleiCao Thanks, yes, the pruning results can depend on quite many factors. Training longer will usually end up a sparser network.
