### ISSUE TITLE
KAN VS MLP for Motor Imagery BCI classification

### ISSUE THREAD

**Issue by JARS29** [KindXiaoming/pykan#183]
I want to share this repo where we evaluate ACC performance between KAN and MLP in four scenarios: RAW Multiclass, RAW Binary, CSP Multiclass, and CSP Binary.

Draw your conclusions (see ours in the report). 

Best!

https://github.com/JARS29/KAN_MLP_MI-BCI

**Comment by AlessandroFlati** [comment]
Which report?
I could only find a notebook, inside "results", which shows approximately the same results, except for one which shows a bit more overfitting on KAN.
