### ISSUE TITLE
One example of obtaining symbolic function by using KAN 

### ISSUE THREAD

**Issue by obisidianouc** [KindXiaoming/pykan#189]
Very interesting work!

I want to contribute an interesting real-world example of using KAN to obtain a symbolic function.

In ocean science, a 75-term expression is used to calculate "density" by using "temperature" and "salinity". I tried to use KAN to find much simpler expression with reasonable accuracy and got good results. The activation shapes also intuitively show that the changes in temperature have more impact on the changes in density compared to salinity.

Example: 
https://github.com/obisidianouc/Kan_example.git

happy to discuss!

**Comment by KindXiaoming** [comment]
Very cool! I wonder what that 75-term expression looks like? And how accurate is the complex formula? Would be cool to plot Pareto Frontiers trading off between accuracy and  simplicity (interpretability).

**Comment by obisidianouc** [comment]
> Very cool! I wonder what that 75-term expression looks like? And how accurate is it? Maybe you can try deeper/wider KANs to get more accuracy but less simplicity. Would be cool to plot Pareto Frontiers trading off between accuracy and simplicity.

75-term expression is here:

https://github.com/obisidianouc/Kan_example/blob/9ae5502f3cac4762e05fa347aac4e870541102c8/75term.ipynb

I am not familiar with Pareto Frontiers trading off. Could you guide me how to make such plots ?

Thanks
