### ISSUE TITLE
KAN for Vision Transformer

### ISSUE THREAD

**Issue by chenziwenhaoshuai** [KindXiaoming/pykan#191]
We are trying to use KAN on ViT to replace MLP for training on ImageNet, and we welcome co-builds!
[Vision-KAN](https://github.com/chenziwenhaoshuai/Vision-KAN)

**Comment by hk-zh** [comment]
Interesting idea! I've come up with a title for you. **Kansformer: What KAN I say?**

**Comment by jloveric** [comment]
Probably TransformerKan

**Comment by chenziwenhaoshuai** [comment]
We are training on ImageNet1k, you can follow my github [Vision KAN](https://github.com/chenziwenhaoshuai/Vision-KAN) repo to see the progress, and I'd appreciate it if you could give me a star!
