### ISSUE TITLE
 UnboundLocalError: local variable 'alpha_mask' referenced before assignment

### ISSUE THREAD

**Issue by HuizhiXu** [KindXiaoming/pykan#192]
When executing self.model.plot(), an error occurs:
**UnboundLocalError: local variable 'alpha_mask' referenced before assignment.**

Upon inspection of [the code](https://github.com/KindXiaoming/pykan/blob/ef4861ebe6160e037f45a32b43950b4fb5fafa52/kan/KAN.py#L633), it indicates that when the necessary conditions are not met, the alpha_mask remains undefined.

![截屏2024-05-15 14 31 27](https://github.com/KindXiaoming/pykan/assets/29792978/484272f0-3b20-4bfe-8e22-d7363870392d)

**Comment by KindXiaoming** [comment]
Hi, what is the value of `symbol_mask` and `numerical_mask` in your case?

**Comment by HuizhiXu** [comment]
Hi, we have finally reproduced the error. We run 30 steps and call the plot function after each training step. The error occurs during the process: when the training error suddenly becomes NaN, the next step is to plot, and then the error occurs. At this point, both the values of `symbol_mask` and `numerical_mask` are NaN.

**Comment by KindXiaoming** [comment]
I see, the nan loss seems like the real bug. Please open another issue for the nan loss if you still have the problem.
