### ISSUE TITLE
Why use SiLU before residual connection

### ISSUE THREAD

**Issue by j93hahn** [KindXiaoming/pykan#198]
Title. In https://github.com/KindXiaoming/pykan/blob/ef4861ebe6160e037f45a32b43950b4fb5fafa52/kan/KANLayer.py#L65, why do you apply SiLU on the input x before passing it through the linear layer and then the residual connection? Why not the linear layer first then SiLU? Or why even use SiLU altogether?

**Comment by LarsDoorenbos** [comment]
Related: https://github.com/KindXiaoming/pykan/issues/128
