### ISSUE TITLE
Using Symbolic formula

### ISSUE THREAD

**Issue by MinSiThu** [KindXiaoming/pykan#209]
After I trained the KAN on the dataset of mnist dataset. And fixed the symbolic formula. I got the symbolic formula from the model. 

Can I just use the symbolic formula as a Python function to classify the data?

**Comment by seyidcemkarakas** [comment]
I have faced same situation on regression case.

You can look up this issue => https://github.com/KindXiaoming/pykan/issues/206
Author also replied it.

**Comment by MinSiThu** [comment]
> I have faced same situation on regression case.
> 
> 
> 
> You can look up this issue => https://github.com/KindXiaoming/pykan/issues/206
> 
> Author also replied it.

Thank you, it is really helpful.
