### ISSUE TITLE
I already seed, but the result also show difference.

### ISSUE THREAD

**Issue by mosimod** [KindXiaoming/pykan#210]

**Comment by KindXiaoming** [comment]
could you provide how different are the results?

**Comment by yyugogogo** [comment]
I encountered the same issue while trying to reproduce the result from hellokan.ipynb. Here are the results with exactly the same setting (I output the result right after the `auto_symbolic` function) :

![result1](https://github.com/KindXiaoming/pykan/assets/169964123/1fcafd3d-2cce-497a-9d45-54bb8fd11362)
![result2](https://github.com/KindXiaoming/pykan/assets/169964123/f88df0b8-72d0-4d57-8db0-99c1aacda593)

**Comment by KindXiaoming** [comment]
Relate: https://github.com/KindXiaoming/pykan/issues/258
