### ISSUE TITLE
Is KAN particularly not good at fitting the multiplication operations?

### ISSUE THREAD

**Issue by SimingShan** [KindXiaoming/pykan#212]
Hi, what an interesting work! However, during my experiments, i found that KAN is particularly not very good at the multiplications, or maybe it is just the way i implement it is not quite right. For example, the most simple problem of x * y, and i set my experiment to be
`model = KAN(width=[2,2,1], grid=5, k=3)` (which I assume is the same as the paper)
`f = lambda x:x[:,[0]] * x[:,[1]]`
`dataset = create_dataset(f, n_var=2)`
then train the model by 
`# model.train(dataset, opt="LBFGS", steps=200, lamb=0.00);`
and the result turns out to be like this
<img width="304" alt="1715975044451" src="https://github.com/KindXiaoming/pykan/assets/81949413/f1378b62-d0b8-4b96-b57b-9f2c3ce85de8">
which is quite different with the paper. I have also tried other hyper-parameters, but still didn't work out, which part of my code is wrong?

**Comment by KindXiaoming** [comment]
I would count this as a success. (0,0,0) -> linear, (0,0,1) -> quadratic, (0,1,0) -> linear, (0,1,1) -> quadratic. (1,0,0) -> quadratic, (1,1,0) -> linear. Although the quadratic functions are not symmetric, but this is a random gauge degree of freedom. You may try varying random seeds; if you are lucky, you can get symmetry parabola.

$x^2$

**Comment by KindXiaoming** [comment]
The must recent update include multiplication operators in KANs.
Example: https://github.com/KindXiaoming/pykan/blob/master/tutorials/Interp_1_Hello%2C%20MultKAN.ipynb

**Comment by SimingShan** [comment]
> The must recent update include multiplication operators in KANs. Example: https://github.com/KindXiaoming/pykan/blob/master/tutorials/Interp_1_Hello%2C%20MultKAN.ipynb

WOW, I can't believe you replied me after two months, thanks brother!
