### ISSUE TITLE
Proof of the Theorem 2.1

### ISSUE THREAD

**Issue by aprilbian** [KindXiaoming/pykan#213]
Could anyone remind me how to prove the Theorem 2.1?  I can hardly understand the effect on the superscript G on functions, \Phi_j. Moreover, the notation of C^m norm seems unfamilar to me, is it often used in machine learning literatures?

**Comment by KindXiaoming** [comment]
G basically refers that it's a smooth function but approximated by a grid of finite size G. C^m is widely in math.
