### ISSUE TITLE
Training KAN on a diabetes classification dataset

### ISSUE THREAD

**Issue by Chukwuebuka-2003** [KindXiaoming/pykan#217]
Now, I tried to train the KAN on a dataset that deals on classification. 

My question are these:

![image](https://github.com/KindXiaoming/pykan/assets/56232734/1f3319e6-91ba-4564-ab44-0afa64e7cb26)

![image](https://github.com/KindXiaoming/pykan/assets/56232734/f4ff7f35-5fb9-4281-b9db-665e43007297)

![image](https://github.com/KindXiaoming/pykan/assets/56232734/4ef98a02-c05f-4de8-a624-9366b79cba2a)

![image](https://github.com/KindXiaoming/pykan/assets/56232734/bda151cc-6245-4b91-b960-9297fdfc6c89)

![image](https://github.com/KindXiaoming/pykan/assets/56232734/80a68845-acd5-4926-870b-38625f487ed4)

Now when I tried to run this: 

![image](https://github.com/KindXiaoming/pykan/assets/56232734/4d750cf7-f580-4cde-bdf8-f92f895d1bb8)

This was the error that I was seeing: ValueError: array must not contain infs or NaNs

I'm currently stuck here:
![image](https://github.com/KindXiaoming/pykan/assets/56232734/776df14a-5aeb-46a6-a79b-121c8fd5eba1)

**Comment by KindXiaoming** [comment]
hi, does `model.train()` work well (doesn't show any NaN)? Can you nail down to whether the problem comes from `train` or `auto_symbolic`.

**Comment by ChrisD-7** [comment]
I tried it on a SCM dataset and my RAM gets full whatas ur specs

**Comment by ChrisD-7** [comment]
@KindXiaoming i think his issue is with the auto_symbolic function cuz it looks like his model is trained and pruned

**Comment by Chukwuebuka-2003** [comment]
@KindXiaoming I do think that this issue might be from the auto_symbolic.

Like @ChrisD-7 said, the model has been trained and pruned.

**Comment by ChrisD-7** [comment]
yup the low  visualization is not that good for classification probs


![image](https://github.com/KindXiaoming/pykan/assets/157317426/1d358cd2-10be-4534-92eb-98593ab713e0)

**Comment by Chukwuebuka-2003** [comment]
The dataset that I used isn't big but a little dataset used to train and test classification models. I will share my notebook

**Comment by ChrisD-7** [comment]
I ran a model and will share it as well will link my repo

**Comment by ChrisD-7** [comment]
@Chukwuebuka-2003  take a look : https://github.com/ChrisD-7/Fraud-Detection-in-Supply-Chains-with-Kolmogorov-Arnold-Networks

**Comment by Chukwuebuka-2003** [comment]
@ChrisD-7  I was able to run it, but I came across related errors

Here's the link to my repo on this: https://github.com/Chukwuebuka-2003/kan_diabetes

**Comment by ChrisD-7** [comment]
@Chukwuebuka-2003 let me take a look

**Comment by ChrisD-7** [comment]
**@Chukwuebuka-2003 I have submitted a pull request. Please let me know if there are any additional changes needed:**

![image](https://github.com/KindXiaoming/pykan/assets/157317426/118e4ec4-c26a-4023-b2af-31c1553ca4b2)

**@KindXiaoming I believe this issue can now be closed. The model is functioning well and achieved around 80% accuracy. I encountered some issues with converting the formula to NumPy, but I managed to resolve them.**
