### ISSUE TITLE
PDE Modelling, more complex benchmarks

### ISSUE THREAD

**Issue by dario-coscia** [KindXiaoming/pykan#22]
Hi! Amazing work, the PDEs modelling with Physics Informed Neural Network seems to be a breakthrough by looking at the root mean square error.

I wanted to ask if you tried more complex PDEs, e.g Burgers, Navier Stokes, KdV?

If you are interest we could collaborate to put KAN layer in [PINA](https://github.com/mathLab/PINA) which is a versatile software for equation learning, and try more complex benchmarks! Thanks for the work🚀🚀

**Comment by KindXiaoming** [comment]
Hi, Thanks for reaching out! Our PDE results are still quite preliminary and PDE solving may not be *my* main focus in the future, but I'm sure people in the community (like you!) will develop better tools and interface for KANs for PDE solving. My collaborators may also be interested in extending this, but that's probably for a separate project. PINA looks like real charm, would have loved to contribute if I had time. Thank you!
