### ISSUE TITLE
What does `reg` mean when training?

### ISSUE THREAD

**Issue by egmaminta** [KindXiaoming/pykan#221]
Hi! I would like to ask what does `reg` mean when training KAN? For example you would see something like:

`train loss: xxx | test loss: yyy | reg: zzz : ...`

And why is it always changing? Does this refer to the lambda or overall regularization parameter?

**Comment by KindXiaoming** [comment]
sorry for the confusion. reg means the regularization term after the lambda coefficient. Regularization could include l1, entropy, etc.

**Comment by egmaminta** [comment]
Oh I see... if `reg` is the regularization term, shouldn't it be equal to zero if I set the lambda coefficient (the coefficient that refers to the overall regularization magnitude) equal to zero as well?

**Comment by KindXiaoming** [comment]
oh sorry, so the displayed one is before applying the coefficient, i.e., `real reg = lamb * reg`
