### ISSUE TITLE
Performance of KAN in some image classification datasets

### ISSUE THREAD

**Issue by Boreuseful** [KindXiaoming/pykan#224]
Compare the performance of  pykan, efficient-kan, and FastKAN with MLP on image classification tasks using the MNIST, CIFAR10, and CIFAR100 datasets.Additionally, include the differences in training time between FastKAN and efficient-kan.
![kan_Image_Classification](https://github.com/KindXiaoming/pykan/assets/121753445/fe8fffa2-672e-4d84-853c-1add329a2862)

**Comment by fangkuoyu** [comment]
Boreuseful: Thanks for the benchmark. I have one question: CIFAR10 KAN Case #1 and Case #2 have the network shape as (784, 10, 10) and (784, 20, 10). I am wondering if it is a typo in 784, because the image shape of CIFAR10 is 32 x 32 x 3.

**Comment by MrMois** [comment]
Thanks for the benchmark! What does iterate mean? is it the number of parameter updates (aka optim.step())?

**Comment by bulaikexiansheng** [comment]
@Boreuseful Thanks for your benchmark! Could you share your code? I want to compare the performance between MLP and KAN. But i find that memory error happening if i do not resize the minist image from [1, 28, 28] to [1, 7, 7]. And the accuracy of KAN is about 77.89%, mlp is about 91.76 %. The results are blow:
![image](https://github.com/KindXiaoming/pykan/assets/58812562/13fbf5d7-add5-4518-ab20-c66df5cf0804)

**Comment by yhaddbb** [comment]
Thanks for your benchmark. I have a question, how to statistic the model parameters? Is it by torchsummary?

**Comment by KindXiaoming** [comment]
Thanks for the results!
