### ISSUE TITLE
How to Use Multi-GPU？

### ISSUE THREAD

**Issue by BraudoCC** [KindXiaoming/pykan#231]
I wanner fit KAN with multi gpus, how to make it by  nn.DataParallel(model)?

**Comment by FulingChen** [comment]
You can't use dataparallel or multiprocess. I tried to use mp, but ending up with each gpu took the same work load.

**Comment by BraudoCC** [comment]
您好，我已收到您的邮件，我会在看到邮件内容后第一时间处理，祝您生活愉快！

**Comment by KindXiaoming** [comment]
something to be solved in the future :)

**Comment by BraudoCC** [comment]
您好，我已收到您的邮件，我会在看到邮件内容后第一时间处理，祝您生活愉快！
