### ISSUE TITLE
I fixed all random seeds. But the result is still different

### ISSUE THREAD

**Issue by yyugogogo** [KindXiaoming/pykan#236]
Hi author, congrats on the fantastic work. But when I tried to reproduce your result in hellokan.ipynb, I found the results are different in different runtime though I've fixed all settings including random seed in `create_dataset` and KAN initialization. Btw, I output the result right after `auto_symbolic` function is called (as you suggested in another issue). I wonder what causes the result to be different from each other?

![result2](https://github.com/KindXiaoming/pykan/assets/169964123/8a0c4a87-30c1-455e-a043-ce621acb03b8)
![result1](https://github.com/KindXiaoming/pykan/assets/169964123/f564acd1-1603-453d-9960-2e82f59b2c05)

**Comment by yyugogogo** [comment]
Hi Xiaoming, thank you for your timely reply! I tried (1) and (2), but neither works, the results are still different. I'm confused about what causes the randomness in the result since I've fixed all random seeds (Maybe I missed out some)?. I've attached my code for your reference. Thanks! 
[KAN.zip](https://github.com/KindXiaoming/pykan/files/15452540/KAN.zip)


> it looks like you are running in jupyter notebook, what about (1) you restart the notebook and then rerun (2) without restarting the notebook and rerun I'm more confident that you'll at least get (1) correct?

**Comment by KindXiaoming** [comment]
Hi, I also remembered that LBFGS have some weird source of randomness. How about switching to Adam (you need train longer to make it work)?

**Comment by yyugogogo** [comment]
Hi, thanks for your help! I've fixed the problem by

1. Using float64 by adding torch.set_default_dtype(torch.float64) in the beginning of my code (need to edit KANLayer.py to avoid TypeError)
2. Replacing LBFGS with Adam
3. Running in .py script instead of notebook

Thank you again for your help!
