### ISSUE TITLE
It looks like the description mismatch of the code

### ISSUE THREAD

**Issue by sheiy** [KindXiaoming/pykan#244]
https://kindxiaoming.github.io/pykan/API_demo/API_9_video.html
<img width="953" alt="image" src="https://github.com/KindXiaoming/pykan/assets/12210038/5b5a26ab-a5b3-44d1-949b-6da5a2e5b075">

**Comment by KindXiaoming** [comment]
you're right, this description was copied from the exp(sin(pi*x)+y^2) [2,5,1] case.
