### ISSUE TITLE
How to use grid extention technique when Solving Partial Differential Equation

### ISSUE THREAD

**Issue by yanyuechuixue** [KindXiaoming/pykan#245]
It will be very helpfull if we use a small grid to get a roughly solution and then add more grid to make the solution better.

Thank you very much!

**Comment by KindXiaoming** [comment]
hi this might be helpful: https://github.com/KindXiaoming/pykan/blob/master/tutorials/Example_6B_PDE.ipynb

**Comment by yanyuechuixue** [comment]
Thank you very much.
I am sorry. I haven't notice that file has been updated two weeks ago.
