### ISSUE TITLE
Importance of input features

### ISSUE THREAD

**Issue by batmanvane** [KindXiaoming/pykan#247]
How would you calculate importance of input features. I thought something based on self.acts_scale which for each layer l has dimension input_l x output_l - which i think is also done for scaling opacity in self.plot()? Any suggestions? So far I am summing self.acts_scale[0][inputfeature] to derive a measure of importance for each inputfeature.

**Comment by KindXiaoming** [comment]
This is reasonable for [x, 1, 1] KANs (as in the knot example). For wider or deeper KANs, such thing can be misleading. For example, a variable could have large impact, but through multiple layers (so the first layer could have small impact). So ideally one would want not only the scale of the first layer, but also aggregate the impact of following layers.

**Comment by batmanvane** [comment]
yes, indeed. i now matrixmultiply over all layers. works ok. what about self.acts_scale_std? is this a measure sensitivity of the l1 norm regarding which variation?

**Comment by seyidcemkarakas** [comment]
> [0][inputfeature]

@batmanvane Can you give us information about **acts_scale** and **acts_scale_std**.
How can we use it in order to see feature importances ?

Can you share a code or anything else?

Thanks

**Comment by KindXiaoming** [comment]
@batmanvane self.acts_scale_std is just self.acts_scale but removing bias. In some cases, an activation function learns to be a non-zero constant function (non-zero acts_scale but zero acts_scale_std). Depending on your view, you think think it's important (non-zero acts_scale) or not (zero acts-scale_std).

**Comment by FulingChen** [comment]
I had multiple layers. I calculate the feature importance by using self.acts_scale[0] x self.acts_scale[1] x .... x self.acts_scale[n]. Not sure if it is correct.

**Comment by seyidcemkarakas** [comment]
> I had multiple layers. I calculate the feature importance by using self.acts_scale[0] x self.acts_scale[1] x .... x self.acts_scale[n]. Not sure if it is correct.

Can you give me your code and/or your case ? I mean your model architecture.

**Comment by seyidcemkarakas** [comment]
@KindXiaoming  Here is my case:

My KAN model is (regression case)=> 
```python
model = KAN(width=[14,5,1], grid=3, k=11)

```

and here is what I have understand from this issue page => 

```python
layer_1 = model.acts_scale[0].detach().numpy()
layer_2 = model.acts_scale[1].detach().numpy()
np.dot(layer_1.T, layer_2.T)
Output =>array([[ 0.88495725],
       [ 2.8139446 ],
       [ 1.5284556 ],
       [ 3.4714272 ],
       [ 0.33114597],
       [ 1.0129826 ],
       [ 0.3477646 ],
       [ 0.9727632 ],
       [13.910817  ],
       [ 8.687671  ],
       [ 0.3236578 ],
       [ 1.3944976 ],
       [ 0.944427  ],
       [ 0.11070064]], dtype=float32)
```

I have got 14 input features and now ı have got 14 values. Do they represent the Importance of my 14 features ?

**Comment by FulingChen** [comment]
Similar to what you have done. My model is [1393,30,5,1]. 

torch.matmul(torch.matmul(model.acts_scale[0].T, model.acts_scale[1].T),model.acts_scale[2].T)

The final output array would be in shape of [1391,1]


> @KindXiaoming Here is my case:
> 
> My KAN model is (regression case)=>
> 
> ```python
> model = KAN(width=[14,5,1], grid=3, k=11)
> ```
> 
> and here is what I have understand from this issue page =>
> 
> ```python
> layer_1 = model.acts_scale[0].detach().numpy()
> layer_2 = model.acts_scale[1].detach().numpy()
> np.dot(layer_1.T, layer_2.T)
> Output =>array([[ 0.88495725],
>        [ 2.8139446 ],
>        [ 1.5284556 ],
>        [ 3.4714272 ],
>        [ 0.33114597],
>        [ 1.0129826 ],
>        [ 0.3477646 ],
>        [ 0.9727632 ],
>        [13.910817  ],
>        [ 8.687671  ],
>        [ 0.3236578 ],
>        [ 1.3944976 ],
>        [ 0.944427  ],
>        [ 0.11070064]], dtype=float32)
> ```
> 
> I have got 14 input features and now ı have got 14 values. Do they represent the Importance of my 14 features ?

**Comment by batmanvane** [comment]
> @batmanvane self.acts_scale_std is just self.acts_scale but removing bias. In some cases, an activation function learns to be a non-zero constant function (non-zero acts_scale but zero acts_scale_std). Depending on your view, you may think it's important (non-zero acts_scale) or not (zero acts-scale_std).

thanks for clarifying. i think in this case acts_scalt_std may be better suited to order relativ "information contributions" from features to targets. i will check. what i have noticed is, that i get a relatively different picture comparing kan-based importances to say randomforest or bnn or nn importances. i will post a small example here in a few hours. hope it's okay, even though it's the issue section.

**Comment by seyidcemkarakas** [comment]
> > @batmanvane self.acts_scale_std is just self.acts_scale but removing bias. In some cases, an activation function learns to be a non-zero constant function (non-zero acts_scale but zero acts_scale_std). Depending on your view, you may think it's important (non-zero acts_scale) or not (zero acts-scale_std).
> 
> thanks for clarifying. i think in this case acts_scalt_std may be better suited to order relativ "information contributions" from features to targets. i will check. what i have noticed is, that i get a relatively different picture comparing kan-based importances to say randomforest or bnn or nn importances. i will post a small example here in a few hours. hope it's okay, even though it's the issue section.

Please share your results.

Also I have small quesntion. From this point, ı have got this bar plot using 
```python
layer_1 = model.acts_scale[0].detach().numpy()
layer_2 = model.acts_scale[1].detach().numpy()
np.dot(layer_1.T, layer_2.T)
Output =>array([[ 0.88495725],
       [ 2.8139446 ],
       [ 1.5284556 ],
       [ 3.4714272 ],
       [ 0.33114597],
       [ 1.0129826 ],
       [ 0.3477646 ],
       [ 0.9727632 ],
       [13.910817  ],
       [ 8.687671  ],
       [ 0.3236578 ],
       [ 1.3944976 ],
       [ 0.944427  ],
       [ 0.11070064]], dtype=float32)
```

How can I identify these values ? I am writing an scientific article so I need to indetify these values like an expression .

**Comment by batmanvane** [comment]
you could do something like

```
# Create a DataFrame to hold the feature names and their importances
importances_df = pandas.DataFrame({'feature': X_active.keys(), 'importance': importances})
# Sort the DataFrame by importance in descending order
importances_df = importances_df.sort_values('importance', ascending=False)
# Create a bar plot of the feature importances 
plt.figure(figsize=(10, 6))
plt.barh(importances_df['feature'], importances_df['importance'])
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.title(f'Overall Feature Importances')
# save plot
plt.savefig('KAN_feature.pdf', format='pdf')
plt.show()

```

**Comment by batmanvane** [comment]
ok, so i played around to get some meaningfull importances. before i can draw some conclusion: what is the difference when doing

case A:
`model(datasetFull['train_input'][0].reshape(1,15))
`
vs.
case B:
`model(datasetFull['train_input'])`

in the first case i only get values in 

`model.acts_scale`

whereas 

`model.acts_scale_std`

as nans.

also: `model.acts_scale` case A vs. B differ. Does B represent the cummulated l1 norm wrt. all data passes or the last input data?

attached a diagramm for averaging over the input deck using always 2 input sets to get values in `model.acts_scale_std` also with 1 std indication

```
sampleImportances = []
importances = []
for i in range(0, len(datasetFull['train_input']), 2):  # Step by 2 to get 2 items at a time
    # Get two items from the dataset
    xInput = datasetFull['train_input'][i:i + 2]

    # Check if we actually have 2 items, if not, skip or handle accordingly
    if xInput.shape[0] != 2:
        continue

    # Reshape input to match the expected batch shape for the model
    xInput = xInput.reshape(2, input_dim)  # Assuming each input needs to be (1, 15)

    # Pass the reshaped input to the model
    model(xInput)

    # Get the importances
    importances = torch.mm(model.acts_scale_std[0].transpose(0, 1), model.acts_scale_std[1].transpose(0, 1))
    importances = importances.sum(dim=1).cpu().data.numpy()

    # Append importances to the list
    sampleImportances.append(importances)

# scale  sampleImportances to a 0-1 scale
sampleImportances = np.array(sampleImportances)
sampleImportances = (sampleImportances - sampleImportances.min(axis=0)) / (sampleImportances.max(axis=0) - sampleImportances.min(axis=0))
# calculate the mean importance
overallImportances = np.mean(sampleImportances, axis=0)
# calculate the standard deviation of the importance
overallImportances_std = np.std(sampleImportances, axis=0)
# Create a DataFrame to hold the feature names and their importances
importances_df = pandas.DataFrame({'feature': X_active.keys(), 'overallImportances': overallImportances, 'overallImportances_std': overallImportances_std})
# Sort the DataFrame by importance in descending order
importances_df = importances_df.sort_values('overallImportances', ascending=False)

# Create a bar plot of the feature importances for Y1
plt.figure(figsize=(10, 6))
plt.barh(importances_df['feature'], importances_df['overallImportances'], xerr=importances_df['overallImportances_std'])
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.title(f'Overall Feature Importances')
# save plot
plt.savefig('KAN_feature.pdf', format='pdf')
plt.show()
```
<img width="570" alt="importances_averaged" src="https://github.com/KindXiaoming/pykan/assets/115378760/5195a4a9-c4aa-4cf5-b5a5-0e97f04e0cbf">

**Comment by batmanvane** [comment]
just a quick note: Shapley values, even though computational quite intense - may be a better choice in case you want to get an idea of importance. i see some consistency from the above approach (fast) and  Shapleys as both share common ground, at least for simple architectures.
