### ISSUE TITLE
KAN for Graph Convolutional Network in  Collaborative Filtering (FourierKAN-GCF)

### ISSUE THREAD

**Issue by Jinfeng-Xu** [KindXiaoming/pykan#256]
We propose a FourierKAN-GCF method, which utilizes FourierKAN on GCN in the recommendation field to replace MLP for training on MOOC and Amazon Games datasets (better than NGCF and LightGCN on these two datasets). We look forward to further development of KAN in the recommendation field. [FKAN-GCF](https://github.com/Jinfeng-Xu/FKAN-GCF)

**Comment by KindXiaoming** [comment]
Thanks for sharing!
