### ISSUE TITLE
Poor Performance in Simple One Dimension of Data - Code Issue?

### ISSUE THREAD

**Issue by xinlnix** [KindXiaoming/pykan#257]
Here is my code.
Could you help me figure out the reason?
Thanks a lot.
[colab](https://colab.research.google.com/drive/1i-Y61Ky2pfs-I6f8DU9jESETH3DNJNrC?usp=sharing)

**Comment by KindXiaoming** [comment]
hi since it's 1D data, width = [1,1] is enough.

**Comment by xinlnix** [comment]
> ce it's 1D data, width = [1,1] is enough.

Thanks for your reply. I tried it but the result didn't get better, and the plot become segment as follow picture:
<img width="796" alt="Snipaste_2024-06-04_22-07-53" src="https://github.com/KindXiaoming/pykan/assets/34513146/25627c55-fec7-4def-a67b-617704ad4c20">

**Comment by batmanvane** [comment]
you've got to **scale your data** appropriately! if not possible for features, consider `model.update_grid_from_samples(x)` for your example scaled versions of X, y work just fine even with [1,1,1] and crude grid. here, check [https://colab.research.google.com/drive/1i-Y61Ky2pfs-I6f8DU9jESETH3DNJNrC?usp=sharing](url)

![Unknown](https://github.com/KindXiaoming/pykan/assets/115378760/2a6280d4-ece1-405e-9c61-a5f30b518032)
![Unknown-2](https://github.com/KindXiaoming/pykan/assets/115378760/4a69f7bb-a204-4b82-b7a0-6f4256dbdd1e)
![Unknown-3](https://github.com/KindXiaoming/pykan/assets/115378760/02a5cf91-d8c4-40a7-afa3-2e76ece5da9e)

**Comment by xinlnix** [comment]
@batmanvane Thank you a lot for pointing out the key problem. I need to scale my data before feed my data to KAN.
By the way, the link you shared is the unedited version of my share.
Thanks again for your kind.
