### ISSUE TITLE
Why is it that when I run hellokan, it runs so much differently than expected

### ISSUE THREAD

**Issue by yIJunWangg** [KindXiaoming/pykan#258]
Here's the result of my run
![image](https://github.com/KindXiaoming/pykan/assets/169014584/6ed2aafe-c0bd-4151-a2e3-34552ffba2c7)

**Comment by Crusty-Banana** [comment]
I think this happened because there is still some hidden degree of random in the code (between device). You can try increasing the training set or changing up the seed of the create_dataset() function

**Comment by kingkongabc** [comment]
Same here. Is it possible to be instability with floating point in the implementation of LBFGS?

**Comment by KindXiaoming** [comment]
Adding this line in the beginning helps

```
torch.use_deterministic_algorithms(True)
```

**Comment by KindXiaoming** [comment]
This should be solved with the most up-to-date version. Temporarily close this issue.

**Comment by yIJunWangg** [comment]
> This should be solved with the most up-to-date version 0.2.0. Close this issue for now.

thank you
