### ISSUE TITLE
about dataset input value

### ISSUE THREAD

**Issue by kaneyxx** [KindXiaoming/pykan#263]
Hi, I noticed that your example dataset and default grid range are within the range of [-1, 1]. Should we always try to normalize input value to that range or model will handle by itself?

E.g., Now I have 3 input variables of which range are different. They are [-5, 5] [-4, 4] [-1, 1], I don't know how to initialize the spline grid_eps and grid_range.

**Comment by KindXiaoming** [comment]
Hi, `update_grid_from_samples` handles that. if you use the `train` method, it calls `update_grid_from_samples` every few steps. With that being said, it's still advisible to normalize your data to O(1), although not necessarily strictly in [-1,1].

**Comment by kaneyxx** [comment]
Thanks for kindly answering. 
After training some steps, I suppose that the model has updated grid several times. Is it possible to know current grid range? If yes, does it mean that I don't need update grid manually?
Or, if I want to update the grid by myself,  is it the best way to turn off that update grid argument?

**Comment by KindXiaoming** [comment]
Yes, it is possible to know current grid range by calling `model.act_fun[0].grid`, for later layers, use `model.act_fun[l].grid` with `l=1,2,...`. Yes, it means you don't need to update grid manually. If you are still worrying about this, you can check grids right after initialization the model and after training.

Yes, if you want to update the grid by yourself, you could simply set `train(...., stop_grid_update_step=1000000000)` or any extremely large number.

**Comment by kaneyxx** [comment]
Thank you! This is very helpful for understanding the implementations. I'm applying KAN to my domain to see if I can rediscover the same formula. Interpretability is what I have been concerned about for a long time. Thanks again for this great work!
