### ISSUE TITLE
大佬，这个是啥问题

### ISSUE THREAD

**Issue by TuringWang9527** [KindXiaoming/pykan#280]
![image](https://github.com/KindXiaoming/pykan/assets/153472964/e0efd622-764e-4e32-ad36-7f57321cd606)
单纯的import kan from *不报错，但是我实际应用就报错了，也看不出问题在哪

**Comment by KindXiaoming** [comment]
可以试试这个: https://github.com/KindXiaoming/pykan/issues/163#issuecomment-2184060707

**Comment by TuringWang9527** [comment]
> 可以试试这个: [#163 (comment)](https://github.com/KindXiaoming/pykan/issues/163#issuecomment-2184060707)

已解决，谢谢您
