### ISSUE TITLE
Example 10: Use of lock for Relativity Addition

### ISSUE THREAD

**Issue by Papillon-forest** [KindXiaoming/pykan#295]
```
model.lock(0,[[0,0],[1,0]])
model.plot(beta=10)
```
**Error is:**
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[12], line 1
----> 1 model.plot(beta=10)

File E:\anaconda3\envs\pytorch312\Lib\site-packages\kan\KAN.py:647, in KAN.plot(self, folder, beta, mask, mode, scale, tick, sample, in_vars, out_vars, title)
    645 lock_id = self.act_fun[l].lock_id[j * self.width[l] + i].long().item()
    646 if lock_id > 0:
--> 647     im = plt.imread(f'{folder}/lock.png')
    648     newax = fig.add_axes([0.15, 0.7, 0.15, 0.15])
    649     plt.text(500, 400, lock_id, fontsize=15)

File E:\anaconda3\envs\pytorch312\Lib\site-packages\matplotlib\pyplot.py:2123, in imread(fname, format)
   2121 @_copy_docstring_and_deprecators(matplotlib.image.imread)
   2122 def imread(fname, format=None):
-> 2123     return matplotlib.image.imread(fname, format)

File E:\anaconda3\envs\pytorch312\Lib\site-packages\matplotlib\image.py:1541, in imread(fname, format)
   1534 if isinstance(fname, str) and len(parse.urlparse(fname).scheme) > 1:
   1535     # Pillow doesn't handle URLs directly.
   1536     raise ValueError(
   1537         "Please open the URL for reading and pass the "
   1538         "result to Pillow, e.g. with "
   1539         "``np.array(PIL.Image.open(urllib.request.urlopen(url)))``."
   1540         )
-> 1541 with img_open(fname) as image:
   1542     return (_pil_png_to_float_array(image)
   1543             if isinstance(image, PIL.PngImagePlugin.PngImageFile) else
   1544             pil_to_array(image))

File E:\anaconda3\envs\pytorch312\Lib\site-packages\PIL\ImageFile.py:125, in ImageFile.__init__(self, fp, filename)
    121 self.decodermaxblock = MAXBLOCK
    123 if is_path(fp):
    124     # filename
--> 125     self.fp = open(fp, "rb")
    126     self.filename = fp
    127     self._exclusive_fp = True

**FileNotFoundError: [Errno 2] No such file or directory: './figures/lock.png'**

**Comment by KindXiaoming** [comment]
lock is no longer supported :)
