### ISSUE TITLE
KAN for multi outputs?

### ISSUE THREAD

**Issue by jacktang** [KindXiaoming/pykan#299]
Hello, I read all examples and find that the output is single variable(univariate regression), can KAN solve multivariate regression?

**Comment by jacktang** [comment]
well, I find the example in https://github.com/KindXiaoming/pykan/blob/master/tutorials/physics_informed_kan.ipynb

**Comment by KindXiaoming** [comment]
KAN can take any width which is a list of positive integers, and the last dimension is the output dimension. E.g, KAN(width=[2,10,10,3]) has 3 output dimensions.
