### ISSUE TITLE
pykan for Julia (Jukan)?

### ISSUE THREAD

**Issue by oameye** [KindXiaoming/pykan#3]
Is there a plan to implement the network in julia? Maybe provide an interface with Lux.jl?

**Comment by KindXiaoming** [comment]
Good idea! But not at the top of my priority list, hope someone else would be excited about it. The core of the codes is really actually just a few lines. I spent a lot of time doing visualization and stuff which can be ignored if one cares mostly about performance.

**Comment by oameye** [comment]
I totally understand. I might give it a go later this month.
