### ISSUE TITLE
Error sometimes, get: torch._C._LinAlgError: torch.linalg.lstsq:

### ISSUE THREAD

**Issue by plyu3** [KindXiaoming/pykan#300]

**Comment by plyu3** [comment]
coef = torch.linalg.lstsq(mat.to(device), y_eval.unsqueeze(dim=2).to(device), torch._C._LinAlgError: torch.linalg.lstsq: The least squares solution could not be computed because the input matrix does not have full rank (error code: 5).

**Comment by vrbaj** [comment]
Try torch.set_default_dtype(torch.float64) to enforce float64.. I had the same issue which emerge in pykan 0.1.2. In pykan 0.0.5 (same code) was everything ok
