### ISSUE TITLE
Trouble using symbolic_formula for binary classification

### ISSUE THREAD

**Issue by Yagnik12599** [KindXiaoming/pykan#301]
I have created a binary classification model using KAN, and got accuracy of 1., and now I decided to try the interpretability feature, and used the symbolic_formula, adn tried to get the accuracy to only find that the accuracy dipping to 0.67 (which basically means that the formula is only predicting 1 class i.e 0) according to my dataset.
Any idea what might be causing this issue? I also did F1 score and AUC curve of the trained model, and everything suggests that the classification is working perfectly, then why does symbolic formula not work?

This is the line for auto_symbolic:
```
lib = ['x','x^2','x^3','x^4','exp','log','sqrt','tanh','sin','abs']
kan_model.auto_symbolic(lib=lib)
```

![Screenshot 2024-07-05 at 17 21 59](https://github.com/KindXiao

This is my model.plot() figure:
![Screenshot 2024-07-05 at 17 24 56](https://github.com/KindXiaoming/pykan/assets/114891401/72a0c977-5921-4780-9dcf-6494ca8e5e56)
ming/pykan/assets/114891401/e17f7d36-bef7-44d1-b060-0ac1f026b87b)

**Comment by Euron-ZC** [comment]
I have met similar problems, the formula 's performance is worse than model itself.

**Comment by KindXiaoming** [comment]
It's likely. The 1D functions learned by KANs are not necessarily symbolic, so symbolic snapping may harm performance.
