### ISSUE TITLE
AttributeError: 'MultKAN' object has no attribute 'mask'

### ISSUE THREAD

**Issue by caichang872** [KindXiaoming/pykan#313]
I encountered an error when running to model. prune() model. plot (mask=True)
AttributeError: 'MultKAN' object has no attribute 'mask'

**Comment by Jurio0304** [comment]
There is no 'self.mask' in 'MultKAN' module

**Comment by Jurio0304** [comment]
I changed 'mask' to 'false' to get the result:
![image](https://github.com/KindXiaoming/pykan/assets/61222525/99d92c1b-5151-4eee-b15c-a65a610a6cbe)

**Comment by Fei0823** [comment]
I have the same problem-no attribute 'mask'. Is there anyone know how to solve it?

**Comment by KindXiaoming** [comment]
https://github.com/KindXiaoming/pykan/issues/331
