### ISSUE TITLE
Loading a trained model.

### ISSUE THREAD

**Issue by baardl** [KindXiaoming/pykan#322]
Hi.

Sorry for a very basic question. 
When the model is trained, i guess it is automatically saved to the "model" directory.

How can I re-use that saved model?
I want to run predictions towards a pre-trained model.

I tried to follow this example to learn https://github.com/team-daniel/KAN/blob/master/KAN_classification.ipynb

Bard

**Comment by KindXiaoming** [comment]
Hi, please use loadckpt in kan.ckpt: https://github.com/KindXiaoming/pykan/blob/master/kan/ckpt.py

**Comment by baardl** [comment]
Thank you. That worked :-)
