### ISSUE TITLE
Pykan 0.1.2 : RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by HUSTlwr** [KindXiaoming/pykan#328]
After updating to pykan 0.1.2, when I train KAN with cuda, the RuntimeError will arise.
For example:
```python
from kan import KAN, utils
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = KAN(width=[4,2,1,1], grid=3, k=3, seed=0, device=device )
f = lambda x: torch.exp((torch.sin(torch.pi*(x[:,[0]]**2+x[:,[1]]**2))+torch.sin(torch.pi*(x[:,[2]]**2+x[:,[3]]**2)))/2)
dataset = utils.create_dataset(f, n_var=4, train_num=3000, device=device )
model.train(dataset, opt="LBFGS", steps=50, lamb=5e-5, lamb_entropy=2., device=device );
```
Error info:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[3], line 1
----> 1 model = KAN(width=[4,2,1,1], grid=3, k=3, seed=0, device='cuda')
      2 f = lambda x: torch.exp((torch.sin(torch.pi*(x[:,[0]]**2+x[:,[1]]**2))+torch.sin(torch.pi*(x[:,[2]]**2+x[:,[3]]**2)))/2)
      3 dataset = utils.create_dataset(f, n_var=4, train_num=3000, device='cuda')

File D:\Software\Anaconda\install\envs\pykan\lib\site-packages\kan\MultKAN.py:71, in MultKAN.__init__(self, width, grid, k, mult_arity, noise_scale, scale_base_mu, scale_base_sigma, base_fun, symbolic_enabled, affine_trainable, grid_eps, grid_range, sp_trainable, sb_trainable, device, seed, save_plot_data, sparse_init, auto_save, first_init, ckpt_path, state_id)
     67 for l in range(self.depth):
     68     # splines
     69     scale_base = scale_base_mu * 1 / np.sqrt(width_in[l]) + \
     70                  scale_base_sigma * (torch.randn(width_in[l], width_out[l + 1]) * 2 - 1) * 1/np.sqrt(width_in[l])
---> 71     sp_batch = KANLayer(in_dim=width_in[l], out_dim=width_out[l+1], num=grid, k=k, noise_scale=noise_scale, scale_base=scale_base, scale_sp=1., base_fun=base_fun, grid_eps=grid_eps, grid_range=grid_range, sp_trainable=sp_trainable, sb_trainable=sb_trainable, device=device, sparse_init=sparse_init)
     72     self.act_fun.append(sp_batch)
     74 self.node_bias = []

File D:\Software\Anaconda\install\envs\pykan\lib\site-packages\kan\KANLayer.py:131, in KANLayer.__init__(self, in_dim, out_dim, num, k, noise_scale, scale_base, scale_sp, base_fun, grid_eps, grid_range, sp_trainable, sb_trainable, save_plot_data, device, sparse_init)
    129 else:
    130     mask = 1.
--> 131 self.scale_base = torch.nn.Parameter(torch.ones(in_dim, out_dim, device='cuda') * scale_base * mask).requires_grad_(sb_trainable)  # make scale trainable
    132 #self.scale_base = torch.nn.Parameter(torch.ones(in_dim, out_dim, device=device) * scale_base * mask).requires_grad_(sb_trainable)  # make scale trainable
    133 
    134 #else:
    135 #self.scale_base = torch.nn.Parameter(scale_base.to(device)).requires_grad_(sb_trainable)
    136 self.scale_sp = torch.nn.Parameter(torch.ones(in_dim, out_dim, device=device) * scale_sp * mask).requires_grad_(sp_trainable)  # make scale trainable

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
The version of CUDA and cudnn are:
```
pytorch=2.1.0
cuda=cuda_11.8.0
cudnn=8.9.5
```
But when I backed to pykan 0.05, this error did not happen.
The other packages are listed:
```
Package                   Version
------------------------- --------------
anyio                     4.2.0
argon2-cffi               21.3.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.0.5
async-lru                 2.0.4
attrs                     23.1.0
Babel                     2.11.0
backcall                  0.2.0
beautifulsoup4            4.12.3
bleach                    4.1.0
Brotli                    1.0.9
certifi                   2024.7.4
cffi                      1.16.0
charset-normalizer        3.1.0
colorama                  0.4.6
comm                      0.2.1
contourpy                 1.2.1
cycler                    0.12.1
debugpy                   1.6.7
decorator                 4.4.2
defusedxml                0.7.1
entrypoints               0.4
exceptiongroup            1.2.0
executing                 0.8.3
fastjsonschema            2.16.2
filelock                  3.13.1
fonttools                 4.53.0
fqdn                      1.5.1
fsspec                    2024.3.1
gmpy2                     2.1.2
h11                       0.14.0
httpcore                  1.0.5
httpx                     0.27.0
hydroeval                 0.1.0
idna                      3.7
imageio                   2.34.2
imageio-ffmpeg            0.5.1
importlib-metadata        7.0.1
intel-openmp              2021.4.0
ipykernel                 6.28.0
ipython                   8.15.0
ipython-genutils          0.2.0
ipywidgets                8.1.3
isoduration               20.11.0
jedi                      0.18.1
Jinja2                    3.1.4
joblib                    1.4.2
json5                     0.9.25
jsonpointer               3.0.0
jsonschema                4.19.2
jsonschema-specifications 2023.12.1
jupyter                   1.0.0
jupyter_client            7.4.9
jupyter-console           6.4.4
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.0
jupyter_server            2.14.1
jupyter_server_terminals  0.4.4
jupyterlab                4.0.11
jupyterlab-pygments       0.1.2
jupyterlab_server         2.25.1
jupyterlab_widgets        3.0.11
kiwisolver                1.4.5
lxml                      5.2.2
MarkupSafe                2.1.3
matplotlib                3.6.2
matplotlib-inline         0.1.6
mistune                   2.0.4
mkl                       2021.4.0
mkl-fft                   1.3.8
mkl-random                1.2.4
mkl-service               2.4.0
moviepy                   1.0.3
mpmath                    1.3.0
nbclassic                 1.1.0
nbclient                  0.10.0
nbconvert                 7.10.0
nbformat                  5.10.4
nest-asyncio              1.6.0
networkx                  3.2.1
notebook                  6.5.7
notebook_shim             0.2.3
numpy                     1.24.4
overrides                 7.4.0
packaging                 23.2
pandas                    2.2.2
pandocfilters             1.5.0
parso                     0.8.3
pickleshare               0.7.5
pillow                    10.3.0
pip                       24.0
platformdirs              3.10.0
plotly                    5.22.0
proglog                   0.1.10
prometheus-client         0.14.1
prompt-toolkit            3.0.43
psutil                    5.9.0
pure-eval                 0.2.2
pycparser                 2.21
Pygments                  2.15.1
pykan                     0.1.2
pyparsing                 3.1.2
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-json-logger        2.0.7
pytz                      2024.1
pywin32                   305.1
pywinpty                  2.0.10
PyYAML                    6.0.1
pyzmq                     25.1.2
qtconsole                 5.5.2
QtPy                      2.4.1
referencing               0.30.2
requests                  2.32.2
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.10.6
scikit-learn              1.1.3
scipy                     1.13.1
seaborn                   0.13.2
Send2Trash                1.8.2
setuptools                65.5.0
six                       1.16.0
sniffio                   1.3.0
soupsieve                 2.5
stack-data                0.2.0
sympy                     1.11.1
tbb                       2021.13.0
tenacity                  8.4.2
terminado                 0.17.1
threadpoolctl             3.5.0
tinycss2                  1.2.1
tomli                     2.0.1
torch                     2.2.2
torch-summary             1.4.5
torchaudio                2.3.1
torchvision               0.18.1
tornado                   6.4.1
tqdm                      4.66.2
traitlets                 5.14.3
types-python-dateutil     2.9.0.20240316
typing_extensions         4.11.0
tzdata                    2024.1
uri-template              1.3.0
urllib3                   2.2.2
wcwidth                   0.2.13
webcolors                 24.6.0
webencodings              0.5.1
websocket-client          1.8.0
wheel                     0.43.0
widgetsnbextension        4.0.11
win-inet-pton             1.1.0
zipp                      3.17.0
```

**Comment by dongheChen** [comment]
me too!

**Comment by y0sh1d4** [comment]
I checked this on the docker container `pytorch/pytorch:2.3.0-cuda11.8-cudnn8-runtime`

I have the same issue like this,

```python
import torch
import kan
device = torch.device('cuda')
model = kan.KAN(width=[1,1], grid=3, k=3, seed=0, device=device)

>>> RuntimeError                              Traceback (most recent call last)
Cell In[2], line 2
      1 device = torch.device('cuda')
----> 2 model = kan.KAN(width=[1,1], grid=3, k=3, seed=0, device=device)

File /workspace/pykan/kan/MultKAN.py:72, in MultKAN.__init__(self, width, grid, k, mult_arity, noise_scale, scale_base_mu, scale_base_sigma, base_fun, symbolic_enabled, affine_trainable, grid_eps, grid_range, sp_trainable, sb_trainable, device, seed, save_act, sparse_init, auto_save, first_init, ckpt_path, state_id, round)
     68 for l in range(self.depth):
     69     # splines
     70     scale_base = scale_base_mu * 1 / np.sqrt(width_in[l]) + \
     71                  scale_base_sigma * (torch.randn(width_in[l], width_out[l + 1]) * 2 - 1) * 1/np.sqrt(width_in[l])
---> 72     sp_batch = KANLayer(in_dim=width_in[l], out_dim=width_out[l+1], num=grid, k=k, noise_scale=noise_scale, scale_base=scale_base, scale_sp=1., base_fun=base_fun, grid_eps=grid_eps, grid_range=grid_range, sp_trainable=sp_trainable, sb_trainable=sb_trainable, device=device, sparse_init=sparse_init)
     73     self.act_fun.append(sp_batch)
     75 self.node_bias = []

File /workspace/pykan/kan/KANLayer.py:132, in KANLayer.__init__(self, in_dim, out_dim, num, k, noise_scale, scale_base, scale_sp, base_fun, grid_eps, grid_range, sp_trainable, sb_trainable, save_plot_data, device, sparse_init)
    129 else:
    130     mask = 1.
--> 132 self.scale_base = torch.nn.Parameter(torch.ones(in_dim, out_dim, device=device) * scale_base * mask).requires_grad_(sb_trainable)  # make scale trainable
    133 #else:
    134 #self.scale_base = torch.nn.Parameter(scale_base.to(device)).requires_grad_(sb_trainable)
    135 self.scale_sp = torch.nn.Parameter(torch.ones(in_dim, out_dim, device=device) * scale_sp * mask).requires_grad_(sp_trainable)  # make scale trainable

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

The problem is that the `scale_base` is put on the cpu's memory.
The solution is to add `.to(device)` when the `KanLayer` calling, as follows:

`MultiKAN.py, L72`
```python
- sp_batch = KANLayer(in_dim=width_in[l], out_dim=width_out[l+1], num=grid, k=k, noise_scale=noise_scale, scale_base=scale_base, ...)
+ sp_batch = KANLayer(in_dim=width_in[l], out_dim=width_out[l+1], num=grid, k=k, noise_scale=noise_scale, scale_base=scale_base.to(device), ...)
```

However, we face the next error after the modification:
```python
>>> ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 2
      1 device = torch.device('cuda')
----> 2 model = kan.KAN(width=[1,1], grid=3, k=3, seed=0, device=device)

File /workspace/pykan/kan/MultKAN.py:85, in MultKAN.__init__(self, width, grid, k, mult_arity, noise_scale, scale_base_mu, scale_base_sigma, base_fun, symbolic_enabled, affine_trainable, grid_eps, grid_range, sp_trainable, sb_trainable, device, seed, save_act, sparse_init, auto_save, first_init, ckpt_path, state_id, round)
     82 exec('self.node_bias_0' + " = torch.nn.Parameter(torch.zeros(3,1)).requires_grad_(False)")
     84 for l in range(self.depth):
---> 85     exec(f'self.node_bias_{l} = torch.nn.Parameter(torch.zeros(width_in[l+1],)).requires_grad_(affine_trainable).to(device)')
     86     exec(f'self.node_scale_{l} = torch.nn.Parameter(torch.ones(width_in[l+1],)).requires_grad_(affine_trainable).to(device)')
     87     exec(f'self.subnode_bias_{l} = torch.nn.Parameter(torch.zeros(width_out[l+1],)).requires_grad_(affine_trainable).to(device)')

File <string>:1

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1729, in Module.__setattr__(self, name, value)
   1727 elif params is not None and name in params:
   1728     if value is not None:
-> 1729         raise TypeError(f"cannot assign '{torch.typename(value)}' as parameter '{name}' "
   1730                         "(torch.nn.Parameter or None expected)"
   1731                         )
   1732     self.register_parameter(name, value)
   1733 else:

TypeError: cannot assign 'torch.cuda.FloatTensor' as parameter 'node_bias_0' (torch.nn.Parameter or None expected)
```

This is because the `torch.nn.Parameter` is forcely changed to `torch.Tensor` by `.to('cuda')`.
This could be reploduced by the following code;
```python
import torch
cpu = torch.nn.Parameter(torch.zeros(1,)).to('cpu')
print('cpu: ', type(cpu))
cuda = torch.nn.Parameter(torch.zeros(1,)).to('cuda')
print('cuda: ', type(cuda))

>>> cpu:  <class 'torch.nn.parameter.Parameter'>
>>> cuda:  <class 'torch.Tensor'>
```

To address this issue, we change it to `torch.nn.Parameter(torch.zeros(1, device=torch.device('cuda')))`
We can change the code as follows:

`MultiKAN.py, L85-`
```python
- exec(f'self.node_bias_{l} = torch.nn.Parameter(torch.zeros(width_in[l+1],)).requires_grad_(affine_trainable).to(device)')
- exec(f'self.node_scale_{l} = torch.nn.Parameter(torch.ones(width_in[l+1],)).requires_grad_(affine_trainable).to(device)')
- exec(f'self.subnode_bias_{l} = torch.nn.Parameter(torch.zeros(width_out[l+1],)).requires_grad_(affine_trainable).to(device)')
- exec(f'self.subnode_scale_{l} = torch.nn.Parameter(torch.ones(width_out[l+1],)).requires_grad_(affine_trainable).to(device)')

+ exec(f'self.node_bias_{l} = torch.nn.Parameter(torch.zeros(width_in[l+1], device=device)).requires_grad_(affine_trainable)')
+ exec(f'self.node_scale_{l} = torch.nn.Parameter(torch.ones(width_in[l+1], device=device)).requires_grad_(affine_trainable)')
+ exec(f'self.subnode_bias_{l} = torch.nn.Parameter(torch.zeros(width_out[l+1], device=device)).requires_grad_(affine_trainable)')
+ exec(f'self.subnode_scale_{l} = torch.nn.Parameter(torch.ones(width_out[l+1], device=device)).requires_grad_(affine_trainable)')         
```

After this modifucation, I could make KAN's instance on the GPU memory.

**Comment by dongheChen** [comment]
thank you very much！



---- Replied Message ----
| From | ***@***.***> |
| Date | 07/18/2024 01:59 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [KindXiaoming/pykan] Pykan 0.1.2 : RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (Issue #328) |

I checked this on the docker container pytorch/pytorch:2.3.0-cuda11.8-cudnn8-runtime

I have the same issue like this,

importtorchimportkandevice=torch.device('cuda')
model=kan.KAN(width=[1,1], grid=3, k=3, seed=0, device=device)

>>>RuntimeErrorTraceback (mostrecentcalllast)
CellIn[2], line21device=torch.device('cuda')
---->2model=kan.KAN(width=[1,1], grid=3, k=3, seed=0, device=device)

File/workspace/pykan/kan/MultKAN.py:72, inMultKAN.__init__(self, width, grid, k, mult_arity, noise_scale, scale_base_mu, scale_base_sigma, base_fun, symbolic_enabled, affine_trainable, grid_eps, grid_range, sp_trainable, sb_trainable, device, seed, save_act, sparse_init, auto_save, first_init, ckpt_path, state_id, round)
     68forlinrange(self.depth):
     69# splines70scale_base=scale_base_mu*1/np.sqrt(width_in[l]) + \
     71scale_base_sigma* (torch.randn(width_in[l], width_out[l+1]) *2-1) *1/np.sqrt(width_in[l])
--->72sp_batch=KANLayer(in_dim=width_in[l], out_dim=width_out[l+1], num=grid, k=k, noise_scale=noise_scale, scale_base=scale_base, scale_sp=1., base_fun=base_fun, grid_eps=grid_eps, grid_range=grid_range, sp_trainable=sp_trainable, sb_trainable=sb_trainable, device=device, sparse_init=sparse_init)
     73self.act_fun.append(sp_batch)
     75self.node_bias= []

File/workspace/pykan/kan/KANLayer.py:132, inKANLayer.__init__(self, in_dim, out_dim, num, k, noise_scale, scale_base, scale_sp, base_fun, grid_eps, grid_range, sp_trainable, sb_trainable, save_plot_data, device, sparse_init)
    129else:
    130mask=1.-->132self.scale_base=torch.nn.Parameter(torch.ones(in_dim, out_dim, device=device) *scale_base*mask).requires_grad_(sb_trainable)  # make scale trainable133#else:134#self.scale_base = torch.nn.Parameter(scale_base.to(device)).requires_grad_(sb_trainable)135self.scale_sp=torch.nn.Parameter(torch.ones(in_dim, out_dim, device=device) *scale_sp*mask).requires_grad_(sp_trainable)  # make scale trainableRuntimeError: Expectedalltensorstobeonthesamedevice, butfoundatleasttwodevices, cuda:0andcpu!

The problem is that the scale_base is put on the cpu's memory.
The solution is to add .to(device) when the KanLayer calling, as follows:

MultiKAN.py, L72

-sp_batch=KANLayer(in_dim=width_in[l], out_dim=width_out[l+1], num=grid, k=k, noise_scale=noise_scale, scale_base=scale_base, ...)
+sp_batch=KANLayer(in_dim=width_in[l], out_dim=width_out[l+1], num=grid, k=k, noise_scale=noise_scale, scale_base=scale_base.to(device), ...)

However, we face the next error after the modification:

>>>---------------------------------------------------------------------------TypeErrorTraceback (mostrecentcalllast)
CellIn[2], line21device=torch.device('cuda')
---->2model=kan.KAN(width=[1,1], grid=3, k=3, seed=0, device=device)

File/workspace/pykan/kan/MultKAN.py:85, inMultKAN.__init__(self, width, grid, k, mult_arity, noise_scale, scale_base_mu, scale_base_sigma, base_fun, symbolic_enabled, affine_trainable, grid_eps, grid_range, sp_trainable, sb_trainable, device, seed, save_act, sparse_init, auto_save, first_init, ckpt_path, state_id, round)
     82exec('self.node_bias_0'+" = torch.nn.Parameter(torch.zeros(3,1)).requires_grad_(False)")
     84forlinrange(self.depth):
--->85exec(f'self.node_bias_{l} = torch.nn.Parameter(torch.zeros(width_in[l+1],)).requires_grad_(affine_trainable).to(device)')
     86exec(f'self.node_scale_{l} = torch.nn.Parameter(torch.ones(width_in[l+1],)).requires_grad_(affine_trainable).to(device)')
     87exec(f'self.subnode_bias_{l} = torch.nn.Parameter(torch.zeros(width_out[l+1],)).requires_grad_(affine_trainable).to(device)')

File<string>:1File/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1729, inModule.__setattr__(self, name, value)
   1727elifparamsisnotNoneandnameinparams:
   1728ifvalueisnotNone:
->1729raiseTypeError(f"cannot assign '{torch.typename(value)}' as parameter '{name}' "1730"(torch.nn.Parameter or None expected)"1731                         )
   1732self.register_parameter(name, value)
   1733else:

TypeError: cannotassign'torch.cuda.FloatTensor'asparameter'node_bias_0' (torch.nn.ParameterorNoneexpected)

This is because the torch.nn.Parameter is forcely changed to torch.Tensor by .to('cuda').
This could be reploduced by the following code;

importtorchcpu=torch.nn.Parameter(torch.zeros(1,)).to('cpu')
print('cpu: ', type(cpu))
cuda=torch.nn.Parameter(torch.zeros(1,)).to('cuda')
print('cuda: ', type(cuda))

>>>cpu:  <class'torch.nn.parameter.Parameter'>>>>cuda:  <class'torch.Tensor'>

To address this issue, we change it to torch.nn.Parameter(torch.zeros(1, device=torch.device('cuda')))
We can change the code as follows:

MultiKAN.py, L85-

-exec(f'self.node_bias_{l} = torch.nn.Parameter(torch.zeros(width_in[l+1],)).requires_grad_(affine_trainable).to(device)')
-exec(f'self.node_scale_{l} = torch.nn.Parameter(torch.ones(width_in[l+1],)).requires_grad_(affine_trainable).to(device)')
-exec(f'self.subnode_bias_{l} = torch.nn.Parameter(torch.zeros(width_out[l+1],)).requires_grad_(affine_trainable).to(device)')
-exec(f'self.subnode_scale_{l} = torch.nn.Parameter(torch.ones(width_out[l+1],)).requires_grad_(affine_trainable).to(device)')

+exec(f'self.node_bias_{l} = torch.nn.Parameter(torch.zeros(width_in[l+1], device=device)).requires_grad_(affine_trainable)')
+exec(f'self.node_scale_{l} = torch.nn.Parameter(torch.ones(width_in[l+1], device=device)).requires_grad_(affine_trainable)')
+exec(f'self.subnode_bias_{l} = torch.nn.Parameter(torch.zeros(width_out[l+1], device=device)).requires_grad_(affine_trainable)')
+exec(f'self.subnode_scale_{l} = torch.nn.Parameter(torch.ones(width_out[l+1], device=device)).requires_grad_(affine_trainable)')         

After this modifucation, I could make KAN's instance on the GPU memory.

**Comment by HUSTlwr** [comment]
> I checked this on the docker container `pytorch/pytorch:2.3.0-cuda11.8-cudnn8-runtime`
> 
> I have the same issue like this,
> 
> ```python
> import torch
> import kan
> device = torch.device('cuda')
> model = kan.KAN(width=[1,1], grid=3, k=3, seed=0, device=device)
> 
> >>> RuntimeError                              Traceback (most recent call last)
> Cell In[2], line 2
>       1 device = torch.device('cuda')
> ----> 2 model = kan.KAN(width=[1,1], grid=3, k=3, seed=0, device=device)
> 
> File /workspace/pykan/kan/MultKAN.py:72, in MultKAN.__init__(self, width, grid, k, mult_arity, noise_scale, scale_base_mu, scale_base_sigma, base_fun, symbolic_enabled, affine_trainable, grid_eps, grid_range, sp_trainable, sb_trainable, device, seed, save_act, sparse_init, auto_save, first_init, ckpt_path, state_id, round)
>      68 for l in range(self.depth):
>      69     # splines
>      70     scale_base = scale_base_mu * 1 / np.sqrt(width_in[l]) + \
>      71                  scale_base_sigma * (torch.randn(width_in[l], width_out[l + 1]) * 2 - 1) * 1/np.sqrt(width_in[l])
> ---> 72     sp_batch = KANLayer(in_dim=width_in[l], out_dim=width_out[l+1], num=grid, k=k, noise_scale=noise_scale, scale_base=scale_base, scale_sp=1., base_fun=base_fun, grid_eps=grid_eps, grid_range=grid_range, sp_trainable=sp_trainable, sb_trainable=sb_trainable, device=device, sparse_init=sparse_init)
>      73     self.act_fun.append(sp_batch)
>      75 self.node_bias = []
> 
> File /workspace/pykan/kan/KANLayer.py:132, in KANLayer.__init__(self, in_dim, out_dim, num, k, noise_scale, scale_base, scale_sp, base_fun, grid_eps, grid_range, sp_trainable, sb_trainable, save_plot_data, device, sparse_init)
>     129 else:
>     130     mask = 1.
> --> 132 self.scale_base = torch.nn.Parameter(torch.ones(in_dim, out_dim, device=device) * scale_base * mask).requires_grad_(sb_trainable)  # make scale trainable
>     133 #else:
>     134 #self.scale_base = torch.nn.Parameter(scale_base.to(device)).requires_grad_(sb_trainable)
>     135 self.scale_sp = torch.nn.Parameter(torch.ones(in_dim, out_dim, device=device) * scale_sp * mask).requires_grad_(sp_trainable)  # make scale trainable
> 
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
> ```
> 
> The problem is that the `scale_base` is put on the cpu's memory. The solution is to add `.to(device)` when the `KanLayer` calling, as follows:
> 
> `MultiKAN.py, L72`
> 
> ```python
> - sp_batch = KANLayer(in_dim=width_in[l], out_dim=width_out[l+1], num=grid, k=k, noise_scale=noise_scale, scale_base=scale_base, ...)
> + sp_batch = KANLayer(in_dim=width_in[l], out_dim=width_out[l+1], num=grid, k=k, noise_scale=noise_scale, scale_base=scale_base.to(device), ...)
> ```
> 
> However, we face the next error after the modification:
> 
> ```python
> >>> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> Cell In[2], line 2
>       1 device = torch.device('cuda')
> ----> 2 model = kan.KAN(width=[1,1], grid=3, k=3, seed=0, device=device)
> 
> File /workspace/pykan/kan/MultKAN.py:85, in MultKAN.__init__(self, width, grid, k, mult_arity, noise_scale, scale_base_mu, scale_base_sigma, base_fun, symbolic_enabled, affine_trainable, grid_eps, grid_range, sp_trainable, sb_trainable, device, seed, save_act, sparse_init, auto_save, first_init, ckpt_path, state_id, round)
>      82 exec('self.node_bias_0' + " = torch.nn.Parameter(torch.zeros(3,1)).requires_grad_(False)")
>      84 for l in range(self.depth):
> ---> 85     exec(f'self.node_bias_{l} = torch.nn.Parameter(torch.zeros(width_in[l+1],)).requires_grad_(affine_trainable).to(device)')
>      86     exec(f'self.node_scale_{l} = torch.nn.Parameter(torch.ones(width_in[l+1],)).requires_grad_(affine_trainable).to(device)')
>      87     exec(f'self.subnode_bias_{l} = torch.nn.Parameter(torch.zeros(width_out[l+1],)).requires_grad_(affine_trainable).to(device)')
> 
> File <string>:1
> 
> File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1729, in Module.__setattr__(self, name, value)
>    1727 elif params is not None and name in params:
>    1728     if value is not None:
> -> 1729         raise TypeError(f"cannot assign '{torch.typename(value)}' as parameter '{name}' "
>    1730                         "(torch.nn.Parameter or None expected)"
>    1731                         )
>    1732     self.register_parameter(name, value)
>    1733 else:
> 
> TypeError: cannot assign 'torch.cuda.FloatTensor' as parameter 'node_bias_0' (torch.nn.Parameter or None expected)
> ```
> 
> This is because the `torch.nn.Parameter` is forcely changed to `torch.Tensor` by `.to('cuda')`. This could be reploduced by the following code;
> 
> ```python
> import torch
> cpu = torch.nn.Parameter(torch.zeros(1,)).to('cpu')
> print('cpu: ', type(cpu))
> cuda = torch.nn.Parameter(torch.zeros(1,)).to('cuda')
> print('cuda: ', type(cuda))
> 
> >>> cpu:  <class 'torch.nn.parameter.Parameter'>
> >>> cuda:  <class 'torch.Tensor'>
> ```
> 
> To address this issue, we change it to `torch.nn.Parameter(torch.zeros(1, device=torch.device('cuda')))` We can change the code as follows:
> 
> `MultiKAN.py, L85-`
> 
> ```python
> - exec(f'self.node_bias_{l} = torch.nn.Parameter(torch.zeros(width_in[l+1],)).requires_grad_(affine_trainable).to(device)')
> - exec(f'self.node_scale_{l} = torch.nn.Parameter(torch.ones(width_in[l+1],)).requires_grad_(affine_trainable).to(device)')
> - exec(f'self.subnode_bias_{l} = torch.nn.Parameter(torch.zeros(width_out[l+1],)).requires_grad_(affine_trainable).to(device)')
> - exec(f'self.subnode_scale_{l} = torch.nn.Parameter(torch.ones(width_out[l+1],)).requires_grad_(affine_trainable).to(device)')
> 
> + exec(f'self.node_bias_{l} = torch.nn.Parameter(torch.zeros(width_in[l+1], device=device)).requires_grad_(affine_trainable)')
> + exec(f'self.node_scale_{l} = torch.nn.Parameter(torch.ones(width_in[l+1], device=device)).requires_grad_(affine_trainable)')
> + exec(f'self.subnode_bias_{l} = torch.nn.Parameter(torch.zeros(width_out[l+1], device=device)).requires_grad_(affine_trainable)')
> + exec(f'self.subnode_scale_{l} = torch.nn.Parameter(torch.ones(width_out[l+1], device=device)).requires_grad_(affine_trainable)')         
> ```
> 
> After this modifucation, I could make KAN's instance on the GPU memory.

Thanks! It works.

**Comment by KindXiaoming** [comment]
Related: https://github.com/KindXiaoming/pykan/issues/354
