### ISSUE TITLE
NameError: name 'create_dataset' is not defined

### ISSUE THREAD

**Issue by jeqcho** [KindXiaoming/pykan#333]
When following the [hellokan.ipynb](https://github.com/KindXiaoming/pykan/blob/master/hellokan.ipynb) tutorial the second cell throws an error

`NameError: name 'create_dataset' is not defined`

The first two cells are

```
from kan import *
# create a KAN: 2D inputs, 1D output, and 5 hidden neurons. cubic spline (k=3), 5 grid intervals (grid=5).
model = KAN(width=[2,5,1], grid=5, k=3, seed=0)

# create dataset f(x,y) = exp(sin(pi*x)+y^2)
f = lambda x: torch.exp(torch.sin(torch.pi*x[:,[0]]) + x[:,[1]]**2)
dataset = create_dataset(f, n_var=2)
dataset['train_input'].shape, dataset['train_label'].shape
```

It seems like some refactoring has been done since the tutorial is written. Replace the second last line with the `utils` prefix solves the error
```
dataset = utils.create_dataset(f, n_var=2)
```

**Comment by KindXiaoming** [comment]
Thanks for reporting the error! The most recent version should solve this problem.
