### ISSUE TITLE
Intel MKL ERROR: Parameter 4 was incorrect on entry to SGELSY.

### ISSUE THREAD

**Issue by ijazaslamsha** [KindXiaoming/pykan#338]
I am trying to play around with the Example_4_classfication.ipynb notebook. I have a dataset with about 230 features. 

Almost most of the code is unchanged except this bit and the data itself:

```Python
model = KAN(width=[230, 115, 2], grid=3, k=3)

def train_acc():
    return torch.mean((torch.argmax(model(dataset['train_input']), dim=1) == dataset['train_label']).type(dtype))

def test_acc():
    return torch.mean((torch.argmax(model(dataset['test_input']), dim=1) == dataset['test_label']).type(dtype))

results = model.fit(dataset, steps=20, metrics=(train_acc, test_acc), loss_fn=torch.nn.CrossEntropyLoss());
```

When i hit run, I get this error

```Python

description:   0%|                                                           | 0/20 [00:00<?, ?it/s]


Intel MKL ERROR: Parameter 4 was incorrect on entry to SGELSY.
```

Is my model too shallow or is my problem with the data itself?

If it helps, there are a some features with NaN values. I am used to working with XGboost and the NaN values don't cause a problem there. I'm not entirely sure if that's the case here.

**Comment by KindXiaoming** [comment]
yes, nan can cause problems in KAN
