### ISSUE TITLE
miss sum_symbol.png

### ISSUE THREAD

**Issue by ElevenMorning** [KindXiaoming/pykan#341]
<img width="1273" alt="截屏2024-07-15 10 39 24" src="https://github.com/user-attachments/assets/570648c9-b1a9-470c-bfbb-7468b5366cfd">

**Comment by KindXiaoming** [comment]
there seems a problem when installing with pypi.

You may manually fix this by downloading the two png files from [here](https://github.com/KindXiaoming/pykan/tree/master/kan/assets/img) and put in the folder /user/local/.../kan/assets/img.

**Comment by fbkoroglu** [comment]
@KindXiaoming 

I also came across with this problem. I do not know why but the manual fix is working. As far as I observed, during the installation process, the setup code does not creating a folder named as assets and a subfolder img

**Comment by MeDott29** [comment]
maybe the path is mis-labeled?  the package name is pykan but the path says 'usr/local/lib/python3.10/dist-packages/kan'
