### ISSUE TITLE
What does George-Lorentz Varian mean to KAN?

### ISSUE THREAD

**Issue by yuedajiong** [KindXiaoming/pykan#35]
![image](https://github.com/KindXiaoming/pykan/assets/52232153/ac1a6b6d-14ab-4bd9-883b-996078579270)

simpler architecture?

**Comment by KindXiaoming** [comment]
George-Lorentz seem to imply that outer functions can be shared. This may save some parameters but may also lose some expressiveness. Good point though! But might need more thinking!

**Comment by yuedajiong** [comment]
谢谢大神！
继续深入学习这么牛逼的东西。
