### ISSUE TITLE
Why model performs better using multiplication than summation in some cases

### ISSUE THREAD

**Issue by ChenJY-L** [KindXiaoming/pykan#363]
Hi there. 

I am a beginer of KAN and ML. I am trying to use **Mult KAN** in regression task with 6 inputs and 1 output. 
In my case, the relationship between inputs and output is linear most of the time. (As shown in image bellow, red line is output)
![image](https://github.com/user-attachments/assets/f152cf09-6f44-41f0-bb9e-312772866267)

### Multiplication
After prune and symbolic: 
![download](https://github.com/user-attachments/assets/c264b870-f43d-4282-adec-960dac03d833)

One of validation set: 
![download](https://github.com/user-attachments/assets/c044a2a1-b178-414f-855e-ab968fc13247)

### Summation
After prune and symbolic: 
![download](https://github.com/user-attachments/assets/37061362-4758-4f8b-97ef-c56e314d061e)

One of validation set:
![download](https://github.com/user-attachments/assets/8670af31-4bcb-4b27-95f9-e50d08692edf)

Here is my code
https://github.com/ChenJY-L/My_KAN_test/tree/main

Thank you for your reply and answer!

**Comment by KindXiaoming** [comment]
The fact that multiplication works better than summation (and the first layer functions look linear) might imply that some quadratic behavior beyond linear is desirable?

**Comment by ChenJY-L** [comment]
> The fact that multiplication works better than summation (and the first layer functions look linear) might imply that some quadratic behavior beyond linear is desirable?

Thanks for the quick reply! KAN is an amazing network! And Is there any other method of optimizing the model after fix_symbolic?
（小菜鸡受宠若惊）

**Comment by KindXiaoming** [comment]
I guess there isn't much one can do after fix_symbolic except for training more (optimizing affine parameters). But let me advertise for some new functionalities: if you want, you can expand the width and depth of the network to gain some extra expressive power and do further training:
https://github.com/KindXiaoming/pykan/blob/master/tutorials/Interp_3_KAN_Compiler.ipynb

**Comment by ChenJY-L** [comment]
Thank you~ :-)
