### ISSUE TITLE
train() got an unexpected keyword argument 'opt'

### ISSUE THREAD

**Issue by liuyh-Horizon** [KindXiaoming/pykan#371]
Hi everyone, 

Sorry to bother you, but I got one strange error while training a four-layer KAN for MNIST according to this issue: https://github.com/KindXiaoming/pykan/issues/9#issue-2273890965. I got one TypeError in the training step:

`TypeError: train() got an unexpected keyword argument 'opt'`

I cannot understand what happened. I think this argument exists in the train(). Even though I tried the simplest examples I found from the KAN document, train() also reports the same error. Following is my code. Did I make any mistakes here?

![Screenshot from 2024-07-25 22-54-22](https://github.com/user-attachments/assets/d715391e-b7bd-46d4-897d-1cd4b485fae0)

Thanks a lot for your help!

Best regards

**Comment by liuyh-Horizon** [comment]
Oops, I find out why...... In the newest update, model.train() has been replaced as model.fit()...........

**Comment by aka233** [comment]
> Oops, I find out why...... In the newest update, model.train() has been replaced as model.fit()...........
bro thank you for find reason
