### ISSUE TITLE
cannot import name 'sf2kan' from 'kan.compiler'  when running Interp_3

### ISSUE THREAD

**Issue by Euron-ZC** [KindXiaoming/pykan#373]
I have met the problem of sf2kan, have anyone met similar problem?
![image](https://github.com/user-attachments/assets/26c0db25-feaa-45c0-b992-3cd68e62eef2)

**Comment by Yuanzhuangac** [comment]
Changing from 'sf2kan' to 'expr2kan' may work, since 'sf2kan' is commented in compiler.py.
![aaa](https://github.com/user-attachments/assets/186cc6a1-3abd-488d-a513-6b8d7230886d)

**Comment by DeadZen** [comment]
Changing it to kanpiler works

**Comment by Euron-ZC** [comment]
OK, Thank you.
