### ISSUE TITLE
Discrepancy between number "Dimensionless formula" column and feynman.py definitions?

### ISSUE THREAD

**Issue by DavidEnriqueNieves** [KindXiaoming/pykan#377]
Good morning,

I've noticed that the feynman.py equations are defined with the number of variables matching the original formula in Table 3 of the paper. However, the layouts of the KANs are defined with respect to the "Dimensionless formula" column, meaning that whatever dataset was created off that formula had to be using the number of variables found in the "variables" column instead of however many were defined in feynman.py. 

Now, recreating the formula from the table isn't very hard, but it would be useful if the ranges used for the "Dimensionless formula" datasets were published somewhere for the sake of reproducibility. 

Based off the existing code, I can surmise that for the majority of the datasets created using the "Dimensionless formula", the ranges were set to [-1,1], but I wouldn't be surprised if there were exceptions such as the arguments of trigonometric formulas, positive quantities such as masses (as seen in I.9.18), or arguments of square roots such as in I.37.4.

This doesn't constitute a demand, but more so a suggestion.

**Comment by KindXiaoming** [comment]
Dataset can be found here: https://space.mit.edu/home/tegmark/aifeynman.html. I've been integrating this into the pykan package, but it will take time.

**Comment by DavidEnriqueNieves** [comment]
Thank you. I see that the variable ranges are defined under the column names as `vx_low` and `vx_high`, where x in this case can be any number ranging from 1 to 10. I will assume that for any undefined `vx_low` and `vx_high` values, the ranges are then -1 to 1 correspondingly.
