### ISSUE TITLE
Example 7 breaks on model.refine(grid)

### ISSUE THREAD

**Issue by Twigums** [KindXiaoming/pykan#387]
I'm currently trying to refine my grid using model.refine(), but I ran into this error. When I tried running example 7, the same error appears.

I'm currently using:
- pykan v0.2.4
- torch 2.4.0+cu121
- python 3.12.4.

![image](https://github.com/user-attachments/assets/23d4cc1c-217a-4125-8e58-b0e6f39ced17)

**Comment by KindXiaoming** [comment]
hi, save_plot_data has been renamed to save_act (sorry I haven't updated the tutorial). Please change line 60 to `model.save_act = True` and it should work

**Comment by Twigums** [comment]
can verify this works! thanks!
