### ISSUE TITLE
Linearize first layer

### ISSUE THREAD

**Issue by ijazaslamsha** [KindXiaoming/pykan#394]
I want to linearize my first later and combine the outputs of my first layer to a single activation function in the second layer. Would this be possible. 

i tried initializing the model as linear but when training, the activation functions in the first layer also become non linear. I know this is not the right approach however, i would appreciate any feedback. 

For instance like this:
model = KAN(width=[input_feature_length,1, 1], grid=10, k=2, seed=0, base_fun=lambda x: x, noise_scale = 0.0)

Any help or guidance would be appreciated.

**Comment by chen-erqi** [comment]
you can use the class multiKAN, which contains a base_func identity.

**Comment by KindXiaoming** [comment]
yes, KAN(..., base_fun='identity', ...) should work

**Comment by ijazaslamsha** [comment]
I tried it and it resulted in linear activation on all layers. I was wondering if there was a way where one could have different activation for different layers? For example linear in the first layer and silu on the second.
