### ISSUE TITLE
Size mismatch when using model.prune() in "hellokan" file

### ISSUE THREAD

**Issue by DonSteven** [KindXiaoming/pykan#399]
Hello,
I am trying to run the given file "hellokan" and I meet a problem related to tensor size when I run model = model.prune(). The previous code works fine. 
Could anyone please to figure out this problem?
thanks a lot!!!
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[5], line 1
----> 1 model = model.prune()
      2 model.plot()

File ~\Desktop\pykan2\pykan-master\kan\MultKAN.py:1139, in MultKAN.prune(self, node_th, edge_th)
   1136 if self.acts == None:
   1137     self.get_act()
-> 1139 self = self.prune_node(node_th, log_history=False)
   1140 #self.prune_node(node_th, log_history=False)
   1141 self.forward(self.cache_data)

File ~\Desktop\pykan2\pykan-master\kan\MultKAN.py:1080, in MultKAN.prune_node(self, threshold, mode, active_neurons_id, log_history)
   1077             self.remove_node(l + 1, i, mode='down',log_history=False)
   1079 model2 = MultKAN(copy.deepcopy(self.width), grid=self.grid, k=self.k, base_fun=self.base_fun_name, mult_arity=self.mult_arity, ckpt_path=self.ckpt_path, auto_save=True, first_init=False, state_id=self.state_id, round=self.round)
-> 1080 model2.load_state_dict(self.state_dict())
   1082 width_new = [self.width[0]]
   1084 for i in range(len(self.acts_scale)):

File D:\Anaconda\anaconda\envs\pykan\lib\site-packages\torch\nn\modules\module.py:2153, in Module.load_state_dict(self, state_dict, strict, assign)
   2148         error_msgs.insert(
   2149             0, 'Missing key(s) in state_dict: {}. '.format(
   2150                 ', '.join(f'"{k}"' for k in missing_keys)))
   2152 if len(error_msgs) > 0:
-> 2153     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   2154                        self.__class__.__name__, "\n\t".join(error_msgs)))
   2155 return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for MultKAN:
	size mismatch for act_fun.0.grid: copying a param with shape torch.Size([2, 10]) from checkpoint, the shape in current model is torch.Size([1, 10]).
	size mismatch for act_fun.1.grid: copying a param with shape torch.Size([5, 10]) from checkpoint, the shape in current model is torch.Size([1, 10]).

**Comment by DonSteven** [comment]
![image](https://github.com/user-attachments/assets/fdbb0cd3-611b-46ed-a6ad-9e2800d27829)
![image](https://github.com/user-attachments/assets/3959ffdb-a124-4fad-b2e1-9c0a482584de)
![image](https://github.com/user-attachments/assets/e0d5847a-c9e8-42b2-a598-4dbea0f243cc)
RuntimeError: Error(s) in loading state_dict for MultKAN:
	size mismatch for act_fun.0.grid: copying a param with shape torch.Size([2, 10]) from checkpoint, the shape in current model is torch.Size([1, 10]).
	size mismatch for act_fun.1.grid: copying a param with shape torch.Size([5, 10]) from checkpoint, the shape in current model is torch.Size([1, 10]).

**Comment by KindXiaoming** [comment]
Could you please show all blocks above?

**Comment by DonSteven** [comment]
> Could you please show all blocks above?

Sure! Everything is fine, except for model.prune(). I get the same error when I run model.prune(), model.prune_node() in the "pruning" in the tutorials as well.
![image](https://github.com/user-attachments/assets/c3554821-fa65-43c0-928d-7db8cb587ab5)
![image](https://github.com/user-attachments/assets/c3c6dad3-fc0a-46e9-8895-8419da60070f)
![image](https://github.com/user-attachments/assets/c32a9166-88d6-4e7d-a5f2-b5f8c7f1ceb5)
![image](https://github.com/user-attachments/assets/7138abcb-68ac-418f-8084-c2ba2001f1b3)
------------------------------------------------------------------------------------------
![image](https://github.com/user-attachments/assets/4ee3a5e2-9e4c-4cb4-bf47-b94a269a1fec)
![image](https://github.com/user-attachments/assets/d44b9d29-638c-4f99-8336-4c9186b75e5f)

**Comment by KindXiaoming** [comment]
could you please try deleting the ./model folder, and then rerun everything? Please Make sure to run these blocks in order.

**Comment by DonSteven** [comment]
> could you please try deleting the ./model folder, and then rerun everything? Please Make sure to run these blocks in order.

I tried to update MultKAN to the August 18 version, and now it works lol. Thanks
