### ISSUE TITLE
Э хуй

### ISSUE THREAD

**Issue by SeryojaTolsty** [KindXiaoming/pykan#40]
Как её запустить?

**Comment by xxxAleksandrxxx** [comment]
1. Учишь английский
2. Учишь Питон
3. Идешь запускать модель
👍

**Comment by SeryojaTolsty** [comment]
@xxxAleksandrxxx , и в какой же среде выполняется 3й пункт, умник?

**Comment by DenDy1337** [comment]
Типо нужно импортировать в сам код VS, что в туториале указано? 
Прошу быть терпимее новичек

**Comment by KOLAYDER69** [comment]
Вот этот парень мне помог t.me/pasiba

**Comment by SeryojaTolsty** [comment]
@DenDy1337 , для чего так усложнять? Неужели нельзя было сделать нечто аналогичное обычным мультимодальным моделям? Как с этим общаться?

**Comment by SeryojaTolsty** [comment]
@KOLAYDER69 он есть на ютубе?

**Comment by DenDy1337** [comment]
Cогласен с вашим утверждением Сергей

**Comment by KOLAYDER69** [comment]
> @KOLAYDER69 он есть на ютубе?

Да, вот тут подробный гайд его последний https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by DenDy1337** [comment]
Ебать ты отрикролил, а когда он скажет как сделать?

**Comment by SeryojaTolsty** [comment]
@KOLAYDER69 этот баян был исполнен весьма по-гейски. Хотя, нет смысла удивляться пользователям гитхаба и их нравам.

**Comment by Shtirmann** [comment]
в консоли `pip install pykan`

в среде `from kan import *`

доки с примерами использования: https://kindxiaoming.github.io/pykan/index.html
