### ISSUE TITLE
Range of initial grid

### ISSUE THREAD

**Issue by DonSteven** [KindXiaoming/pykan#401]
Hello,
I'm now creating a MultKan model and here's my code: model = KAN(width=[19, 100, 64, 5], grid=16, k=3, seed=0, grid_eps = 0.)
I try to follow the steps in the tutorials Grid and I want to print out the initial grid of my model using "print(model.act_fun[0].grid)". However, it shows that the range of the grid is not [-1, 1]. Could anyone please to explain why? Thanks a lot!

Btw, another point that confused me is that if you set eps to 0, the grid wouldn't be uniform, according to the tutorials and my experiments. However, it contradicts the comments in KanLayer, Kan and MultKan, which says that "When grid_eps = 0, the grid is uniform; when grid_eps = 1, the grid is partitioned using percentiles of samples."

![屏幕截图 2024-08-09 095808](https://github.com/user-attachments/assets/0338da25-4893-4259-a21a-8e927a1b9025)

**Comment by KindXiaoming** [comment]
The grid is padded such that grid[k]=-1 and grid[-k]=1.

It looks like in the screenshot, the grid is uniform and grid_eps = 0., which agrees with the document. Am I missing something?

**Comment by DonSteven** [comment]
> The grid is padded such that grid[k]=-1 and grid[-k]=1.
> 
> It looks like in the screenshot, the grid is uniform and grid_eps = 0., which agrees with the document. Am I missing something?

Thanks for your reply!
For the second question, the screenshot shows the initial state of the grid, which will be uniform no matter what grid_eps is set to. I think grid_eps start to work when I use update_grid_from_samples. Next, If I choose grid_eps=1, model.act_fun[0].grid will give me uniform grids. If I choose grid_eps=0, I will have non-uniform grids.

![image](https://github.com/user-attachments/assets/959f9979-23b4-482e-82f4-9f5c5f6fff1c)
![image](https://github.com/user-attachments/assets/477c0eb0-f341-41a9-bb5f-1d7ff3550e65)

**Comment by KindXiaoming** [comment]
you're right! documentation needs to be revised
