### ISSUE TITLE
name 'KAN' is not defined

### ISSUE THREAD

**Issue by Linqiunanww** [KindXiaoming/pykan#407]
`import matplotlib.pyplot as plt

from sklearn.datasets import make_moons
import torch
import numpy as np
from sklearn.model_selection import train_test_split
from kan import *
model = KAN(width=[2,2], grid=3, k=3)`

**
![image](https://github.com/user-attachments/assets/4cf7c413-4f7f-4303-acb2-5d6c2bd8fe10)
**

**Comment by Linqiunanww** [comment]
help help

**Comment by MahmoodSpewAfsh** [comment]
How did you solved the error?
I am new to this library
