### ISSUE TITLE
Formula for Number of Trainable Parameters 

### ISSUE THREAD

**Issue by AminMoradiXL** [KindXiaoming/pykan#408]
Hi Ziming, 

I was going through your code and seems like for a KAN model with structure [a,b,c] you have used `num_parameters = G*(a*b+b*c)`.
Shouldn't it be `num_parameters = (G+k)*(a*b+b*c)`? Since in the summation the indices are from `0` to `G+k-1`.

**Comment by KindXiaoming** [comment]
you're absolutely correct! Thanks for catching the error!
