### ISSUE TITLE
kanpiler does not pass device to the model

### ISSUE THREAD

**Issue by Mixpap** [KindXiaoming/pykan#427]
As the title says, using kanpiler on non-cpu device tensor input result into error, i.e.
```
phi,r,t = symbols('phi r t')
phi = 3*t/sqrt(r) 
phi_model = kanpiler([t,r], phi)
phi_model(tr)
```

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

Probably needs to be resolved by giving the device as argument to the kanpiler,
```
phi_model = kanpiler([t,r], phi,device=device)
```
which now throws
`TypeError: expr2kan() got an unexpected keyword argument 'device'`

**Comment by KindXiaoming** [comment]
you can instead `phi_model = kanpiler([t,r], phi).to(device)`

**Comment by Mixpap** [comment]
Yes indeed, thanks!
