### ISSUE TITLE
Why `get_act()` so many times in `update_grid_from_samples()`?

### ISSUE THREAD

**Issue by liqimai** [KindXiaoming/pykan#442]
https://github.com/KindXiaoming/pykan/blob/173dadda8274897d97a7a63518c64caccda65576/kan/MultKAN.py#L691-L693

`self.get_act(x)` seems to have nothing to do with `l`. It should be moved out of the for loop to accelerate grid update by `l` times!

**Comment by KindXiaoming** [comment]
please correct me if I'm wrong - the logic is that: after an early layer is updated, activations need to be re-computed since later layer activations become different due to the update.

**Comment by liqimai** [comment]
Oh, I see. Thanks.
