### ISSUE TITLE
All saved act should be detached

### ISSUE THREAD

**Issue by liqimai** [KindXiaoming/pykan#443]
I try to apply SWA tricks to KAN, which need to `deepcopy()` the model. But got the following error:
```
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment
```

The error is triggered by `self.edge_actscale` and `self.acts_scale_spline` in the following lines:

https://github.com/KindXiaoming/pykan/blob/173dadda8274897d97a7a63518c64caccda65576/kan/MultKAN.py#L803-L820

When saving act, nearly all tensors are detached, except `self.edge_actscale` and `self.acts_scale_spline`. I suggest also detaching them like others if this is not intended not to detach them. e.g.
```python
                self.edge_actscale.append(output_range.detach())
                ...
                self.acts_scale_spline.append((output_range_spline / input_range).detach())
```

**Comment by liqimai** [comment]
`self.acts` and `self.cache_data` have the same issue. They should also be detached.

https://github.com/KindXiaoming/pykan/blob/173dadda8274897d97a7a63518c64caccda65576/kan/MultKAN.py#L768

https://github.com/KindXiaoming/pykan/blob/173dadda8274897d97a7a63518c64caccda65576/kan/MultKAN.py#L781

**Comment by KindXiaoming** [comment]
acts_scale_spline and edge_actscale are later used for regularization hence they need to be maintained in the graph.

**Comment by liqimai** [comment]
Thanks for the explanation.
