### ISSUE TITLE
How to draw svg photo when I am using the Plot function

### ISSUE THREAD

**Issue by glotm** [KindXiaoming/pykan#466]

**Comment by glotm** [comment]
![image](https://github.com/user-attachments/assets/56fadd69-8ff0-4407-abfd-b0b01ca03758)

I am a beginner learning KAN. When I was drawing images, I found that the images were in png format. Is there a way to draw the images in svg vector format?

**Comment by ChenJY-L** [comment]
It can be done using code below

```
model.plot()
plt.gcf().savefig('image.svg',format='svg',dpi=150)

**Comment by glotm** [comment]
> It can be done using code
> 
> ```
> model.plot()
> plt.gcf().savefig('image.svg',format='svg',dpi=150)
> ```

Thank,I success plot svg!
