### ISSUE TITLE
Data type error

### ISSUE THREAD

**Issue by Shuaizhang7** [KindXiaoming/pykan#53]
Thank you very much for your excellent work! I want to try to replace the MLP in my model with KAN. When I import KAN via "from kan import KAN", I find that some variables are changed from float32 to float64.

Therefore, I get this error:
File "/home/shuaizhang/anaconda3/envs/4DGS-KAN/lib/python3.8/site-packages/diff_gaussian_rasterization-0.0.0-py3.8-linux-x86_64.egg/diff_gaussian_rasterization/__init__.py", line 92 , in forward
    num_rendered, color, depth, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
RuntimeError: expected scalar type Float but found Double

I want to know how can I solve this problem?

**Comment by KindXiaoming** [comment]
please try remove set default torch dtype in [kan init file](https://github.com/KindXiaoming/pykan/blob/master/kan/__init__.py). The latest branch has done that, or you can comment that line locally.

**Comment by Shuaizhang7** [comment]
Thanks for your quick reply, this issue has been resolved.
