### ISSUE TITLE
KAN overrides `nn.Module` `train()`

### ISSUE THREAD

**Issue by viktor-ktorvi** [KindXiaoming/pykan#6]
Hi,

KAN overrides the base function `train` ([link](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.train)), and uses it for a different purpose. Someone using KAN, assuming that it acts the same as any `nn.Module`, will encounter an error when calling `model.train()` as they usually would. 

This will lead to issues when combining KAN in a larger module with batchnorms and dropouts which need the `model.train()` call.

For example:
```python
import torch.nn as nn
from kan import KAN

device = "cuda"

model = nn.Sequential(
    nn.Conv1d(3, 8, 3),
    nn.BatchNorm1d(8),
    nn.Dropout1d(),
    # ...
    KAN(width=[8, 8, 3], grid=5, k=3, device=device)
)
model.to(device)

print(model)

for epoch in range(10):
    model.train()
    # train loop
    # ...

    model.eval()
    # eval loop
    # ...

```

This throws an error:

```
File "C:\Users\todos\PycharmProjects\kan-examples\train_error.py", line 18, in <module>
    model.train()
  File "C:\Users\todos\anaconda3\envs\torch_opf_clone\lib\site-packages\torch\nn\modules\module.py", line 2394, in train
    module.train(mode)
  File "C:\Users\todos\anaconda3\envs\torch_opf_clone\lib\site-packages\kan\KAN.py", line 881, in train
    batch_size = dataset['train_input'].shape[0]
TypeError: 'bool' object is not subscriptable
```

**Comment by KindXiaoming** [comment]
Thanks, that's a very good point! I think it's important to make KAN easily combined with other modules. In that case, it might be reasonable to change  the `train` method to a different API? Any suggestion? Maybe `trainKAN`?

**Comment by KindXiaoming** [comment]
Also, the [grid update technique](https://github.com/KindXiaoming/pykan/blob/master/kan/KAN.py#L913) is essential in KAN training. In this case, I guess it's more advisable to define a model as a class and write one's own `train()` method to make sure KAN grids are updated properly.

**Comment by viktor-ktorvi** [comment]
You're gonna be more familiar with the use, but here's my take:

A quick fix would be to just rename the class method, whatever seems reasonable (not `training` though, because it's a property of `nn.Module`  ([link](https://pytorch.org/docs/stable/generated/torch.nn.Module.html))). 

However, I think it's better to have it as a standalone function, more as an example, because, as it is now, it's highly specific to your use case (e.g., progress bar, saving plots (I see it can be disabled, but still)). Anyone else is going to want to implement their own training loop. 

As for `update_grid_from_samples`, I think a good training example script and docs can emphasize it's importance, and then the user can call it himself as in `model.update_grid_from_samples(...)`. What do you think?

Here's an [example script](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/graph_gps.py) from a different library which has a model with a function similar to `update_grid_from_samples` (see [this line](https://github.com/pyg-team/pytorch_geometric/blob/36bc9255901fa4afaf03d55fec913ec56888ed53/examples/graph_gps.py#L120)). As long as the example clearly shows the usage, the user can do it himself.

**Comment by KindXiaoming** [comment]
Thanks! Yeah my concern is that people just call the `train()` method for the combined model, finding it's not working well. I agree with you that it'd be great to have an example to show how users can define their own new class (instead of using `nn.Sequential`) and define their own `train` method. If you are working on that example (like the one you showed above), feel free to PR to upload it to [tutorials](tutorials), but no pressure! :) Also no need to worry about styles (which I can take care of later).

**Comment by kashif** [comment]
I would suggest renaming the `train` method to something like `fit` as the logic of the `train` clashes with the `nn.Module`'s `train`

**Comment by GentleFiona** [comment]
I have encountered some difficulties when trying to train KAN as a module of the combined model. Looking forward to the example you've mentioned!

**Comment by kashif** [comment]
@KindXiaoming  and @GentleFiona I believe your issues are not related to the problem raised in this issue, kindly open another issue as to not confound this problem with something else

**Comment by uxhao-o** [comment]
Can you please tell me if this issue is resolved? I introduced KAN into my model to replace MLP which produced this error.

**Comment by KindXiaoming** [comment]
Sorry too many demos used model.train() as the API, so it is good amount of work to change it to some other API (plus, some users are already familiar with using train() instead of say fit()). It is advised to write your own training loop for the whole model. Or if you don't care about interpretability that much, you may use other repos which may not need grid update, e.g., [ChebyShev KAN](https://github.com/SynodicMonth/ChebyKAN).

**Comment by uxhao-o** [comment]
> Sorry too many demos used `model.train()` as the API, so it is good amount of work to change it to some other API (plus, some users might be already familiar with using `train()` instead of say `fit()`). It is advised to write your own training loop for the whole model. Or if you don't care about interpretability that much, you may use other repos which may not need grid update, e.g., [ChebyShev KAN](https://github.com/SynodicMonth/ChebyKAN).

Thanks

**Comment by jsxzyyl** [comment]
Yes,of course ,i'm struggling in this problem too!!and i use this [https://github.com/Blealtan/efficient-kan/tree/master](url) to success my workflow(resnet3d+kan),but i'm not sure that this is a perfect modification or not.May be i need to learn more theoretical stuff.

**Comment by mayabechlerspeicher** [comment]
The same problem affects model.eval(), too. I wonder how it is possible to change a model that contains KAN layers into eval mode to avoid dropouts. Will that be solved as part of the fix in #205?

**Comment by KindXiaoming** [comment]
The update today (version 0.2.0) changed `model.train()` to `model.fit()`

**Comment by kashif** [comment]
@KindXiaoming  please close this issue
