### ISSUE TITLE
I think "hence beating curse of dimensionality" P8 a little unconvincing

### ISSUE THREAD

**Issue by DrProfNewton** [KindXiaoming/pykan#68]
![Screenshot from 2024-05-04 21-29-29](https://github.com/KindXiaoming/pykan/assets/53360102/0c123fb3-6db7-4c02-81f7-def0b890cdd8)

Obviously, C of Theorem 2.1 is dependent of dimension. There are remarkably a contradiction between the Red box and Blue Box.

**Comment by yuedajiong** [comment]
studying ...

**Comment by KindXiaoming** [comment]
Sorry, $\ell=CN^{-\alpha}$ we meant the scaling exponent $\alpha$ is independent of dimemsion, but C is depedent.

**Comment by zhenghaoxu-gatech** [comment]
Do you have a characterization of the size of the smooth KA representation? E.g., for any Holder/Sobolev/Besov function. If not, then I think this result is not directly comparable with the classical MLP or splines approximation theories since you have to assume a "constant size" smooth KA representation.

**Comment by Jiongcheng-Li** [comment]
> Sorry, ℓ=CN−α we meant the scaling exponent α is independent of dimemsion, but C is depedent.

You did a good job! But I shall hope to see your more serious underlying 
mathematical theory. Discussions and debates are a favourite  way of learning. 

https://zhuanlan.zhihu.com/p/695869050?utm_campaign=shareopn&utm_medium=social&utm_psn=1770095693690294273&utm_source=wechat_session

**Comment by Mshajfv** [comment]
studying

**Comment by yuedajiong** [comment]
@KindXiaoming
   大神，我对这个方向其实也研究很长时间了，是否愿意就这个方向背后的一些 ”更深度和泛化“的思考，交流一下？
   我个人感觉，也做了一些实验，感觉到了一个突破点了。
