### ISSUE TITLE
A question about model.plot() method

### ISSUE THREAD

**Issue by avasyukhin** [KindXiaoming/pykan#70]
When I run examples of code (like from hellokan) method model.plot() didn't plot figures (however parts of it saved inside .figures) but matplotlib running in the same environment produce figures correctly.

**Comment by ChamodDamitha** [comment]
> When I run examples of code (like from hellokan) method model.plot() didn't plot figures (however parts of it saved inside .figures) but matplotlib running in the same environment produce figures correctly.

I am having the same issue. Only activation function figures are saved as separate images inside the **figures** folder. I cannot see the whole plot anywhere. How can I plot that?

**Comment by mkrzywda** [comment]
I have similar problem with matplotlib==3.6.2'.` I upgraded to `3.8.4` and I have this same. But I using terminal environment. When I use notebook/google collab this same code works correctly and save whole figure.

**Comment by ChamodDamitha** [comment]
I could solve the issue by adding `plt.show() `to the end of `plot()` method in `KAN `class. This is why it's only working in notebooks.

**Comment by avasyukhin** [comment]
I think we should add this method call for more consistent behavior in both local and collab environments.

**Comment by mkrzywda** [comment]
Yes, this should be definitely added to.
