### ISSUE TITLE
(not issue) (question) Approximation Abilitiy / 拟合能力

### ISSUE THREAD

**Issue by yuedajiong** [KindXiaoming/pykan#73]
更多变量的就不举例了，我就用一个变量的来示意，多变量高维度可以想见的更复杂。
`sin(x*333-cos(999x+2))-cos(22x+1)/exp(x)/sin(6x*x+1)/55*x`

-1<x<+1, -2<y<+2，函数图像为：
![image](https://github.com/KindXiaoming/pykan/assets/52232153/351a7d0f-235d-4186-9537-03f8fccee0b0)

如果增加上面的三角函数频率到一个很高的值，函数复合更多几层：单增+周期 组合，数据点上和高度离散没有规律的差不多，很难拟合到这个上帝函数，如果组合几十次带有周期的函数就更复杂，虽然这些函数个个连续可微，都还不包含更难的函数。
现实世界还有一定的噪音。
（可以很用心的设计一些组合，让变化更复杂很多。在不同的x区间变化很大。 这里仅仅示意。）

为了增强逼近能力，能够变化的：  layer_deepth,  layer_width/主要？,  spline_grid_number,  spline_order_k
首先最敏感的：order_k 肯定不能太大，k=3是不是算足够大了； 太大对于简单问题和grid一样是否导致过拟合？ 很需要斟酌的超参数了？
其次比较敏感的： grid_number，也不能无限的细分
深度相对变化范围有限： 比如这个问题，从几到几十？
如果要精确的逼近，宽度的合理增加，对精度提升，泛化问题，作用多大？ 好像也只有增加宽度合理一些，也能应对这种高频的快速大变化。

也没有深入去对比MLP等其他的基本的网络building block的拟合能力。

对于这种高频周期函数的task，用:  样条函数+Silu+Linear的组合去fit，即便数学上“存在”，但实际找到那些函数（那些基本函数去复合），很有挑战的样子。

水平有限，欢迎指正。

**Comment by KindXiaoming** [comment]
close for now, feel free to reopen if there's more update. sounds like an open problem which i believe future papers will try to address.
