### ISSUE TITLE
which page of Carl Book does the equation of P8 line 2 follow from?

### ISSUE THREAD

**Issue by Jiongcheng-Li** [KindXiaoming/pykan#78]
![Screenshot from 2024-05-05 14-42-19](https://github.com/KindXiaoming/pykan/assets/168825140/0ac7847e-a72c-4bd4-a70a-6317c40d9edd)

which page of "[A Practical Guide to Splines](http://14.29.193.103:81/pdf/CarlSpline.pdf) (revised ed., Carl De Boor 1978)" [red box] does the equation [green box] of P8 line 2 in your paper follow from? Frankly, I have difficult to find the similar Equation in Carl's Book.
Could you give me a hand ?

**Comment by KindXiaoming** [comment]
it's a new result from our paper
