### ISSUE TITLE
KAN feels hard to learn "Addition"

### ISSUE THREAD

**Issue by ycq091044** [KindXiaoming/pykan#80]
Hello, thanks for the interesting method. I have a fail trial and need some help here.

Using the hellokan.ipynb template, I changed the complex formula into "Addition". With all other parts fixed, it seems the model training loss does not go down and cannot discovers the "Addition" operation.

<img width="863" alt="image" src="https://github.com/KindXiaoming/pykan/assets/22296469/677e7232-b8dd-4965-93ea-68aa61f48963">

<img width="487" alt="image" src="https://github.com/KindXiaoming/pykan/assets/22296469/4644879f-3a11-4f48-91de-36a52e38114e">

<img width="792" alt="image" src="https://github.com/KindXiaoming/pykan/assets/22296469/af8ce6da-9c15-4fde-ae15-fb0a368ebae5">

**Comment by Flecart** [comment]
I think you should do as in `hellokan` you should prune the model, then retrain it, and prune it, until you can't prune it anymore

**Comment by KindXiaoming** [comment]
Hi Sorry, my API can be a bit confusing, but instead of 
```pyhotn
f = lambda x: x[:,0] + x[:,1]
```
it should be 
```pyhotn
f = lambda x: x[:,[0]] + x[:,[1]]
```
instead. If that's still not working, try reduce `lamb`.

**Comment by CoryKornowicz** [comment]
I was also a bit confused about the definition of that lambda, and I redefined it locally as 
`f = lambda x: x[:, 0, np.newaxis] + x[:, 1, np.newaxis]`
to make the return dimension more explicit. You can also replace `np.newaxis` with `None` and the effect is the same.

**Comment by ycq091044** [comment]
Thanks, change into `f = lambda x: x[:,[0]] + x[:,[1]]` works.
