### ISSUE TITLE
KAN for images?

### ISSUE THREAD

**Issue by albusdemens** [KindXiaoming/pykan#88]
Hello, first of all, congratulations for the great work! As far as you know, is it possible to extend the Kolmogorov-Arnold theorem to images? Something like _"If IM is a multivariate continuous (?) [2D] function on a bounded domain, it can be written as a finite composition of continuous [2D] functions"_. If that holds, then KANs have the potential to take as input images too! Taking as a starting point what you observed for PDE, KANs could turn out to be more accurate and more parameter-efficient than MLPs, and potentially CNNs.

I am testing if things work, codewise.

**Comment by yingzhige00** [comment]
Hello, I don’t know how your test results are. I am also very concerned about whether KAN can be applied to images. Can you share it?

**Comment by albusdemens** [comment]
Hello, I have a deadline this friday so I didn't have any time for this. Next week should be better. I'll let you know ASAP

**Comment by epicgzs1112** [comment]
me too!@yingzhige0,@albusdemens.

**Comment by hailuu684** [comment]
I am waiting for all discussions

**Comment by lacie-life** [comment]
Me too!

**Comment by albusdemens** [comment]
I wrote down my thoughts and listed the things that should be considered/tested/solved. Feel free to let me know if you have any comments :) If anyone is interested, we could team up and test things. 
[KAN_images.pdf](https://github.com/KindXiaoming/pykan/files/15249746/KAN_images.pdf)

**Comment by StarostinV** [comment]
Here is the basic implementation of the convolutional layer with KAN, which seems to work just fine on the mnist dataset.  https://github.com/StarostinV/convkan
