### ISSUE TITLE
RuntimeError with einsum() in Tensor Operations

### ISSUE THREAD

**Issue by goknurarican** [KindXiaoming/pykan#95]
I am encountering a `RuntimeError` related to the `einsum()` function during my project where I'm integrating the KAN model with the MNIST dataset. The error message is as follows:

 Steps Leading to the Error:
I am using the KAN model for a project that involves image processing with the MNIST dataset. Here's a brief outline of the steps I've followed in my setup:

1. Model Initialization: Initialized the KAN model with specific layer dimensions.
2. Training Loop: Started the training loop where tensors are processed and passed through the model.
3.Tensor Manipulation: During tensor manipulation involving `einsum()`, the above error was triggered.

It appears the issue arises from a mismatch between expected tensor dimensions by `einsum()` and the actual tensor dimensions provided during execution. The operation was intended to manipulate tensors within a custom training function, but the exact dimensions and the format of the equation might be incorrect or incompatible.

Additional Context
Python version: 3.10.8
PyTorch version 1.8
Environment: Local development environment on macOS M1

**Comment by AlessandroFlati** [comment]
You forgot to add the error message. Also, did you pull latest master version?
