### ISSUE TITLE
CPU without cuda problem 

### ISSUE THREAD

**Issue by rspadim** [KindXiaoming/pykan#96]
~/.local/lib/python3.10/site-packages/kan/KANLayer.py
--> 126             self.scale_base = torch.nn.Parameter(torch.FloatTensor(scale_base).cuda()).requires_grad_(sb_trainable)

when runing device='cpu' and without cuda card, this line is always executed

**Comment by rspadim** [comment]
this one works:

self.scale_base = torch.nn.Parameter(torch.FloatTensor(scale_base)).requires_grad_(sb_trainable)

without .cuda()

**Comment by Jim137** [comment]
Hi,
I have made a PR #91 to resolve this problem.

**Comment by SimoSbara** [comment]
It's solved, check #98.
